"""This module provides functions to convert CML xarray data into other formats such as GeoDataFrames."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/05_data.convert.ipynb.

# %% auto #0
__all__ = ['convert_sublinks_to_gdf']

# %% ../../nbs/05_data.convert.ipynb #c3d4e5f6
import numpy as np
import pandas as pd
import xarray as xr
import geopandas as gpd
from shapely.geometry import LineString

# %% ../../nbs/05_data.convert.ipynb #a7b8c9d0
def convert_sublinks_to_gdf(
    cml: xr.DataArray | xr.Dataset, # CML data
    only_meta: bool = True, # The GeoDataFrame will only contain metadata
    offset: float = 2e-4, # Perpendicular offset in degrees (2e-4 ~ 20m in the equator) in order to avoid overlap in visualization
) -> gpd.GeoDataFrame:
    """Convert CML to a GeoDataFrame assuming EPSG:4326 projection"""
    if only_meta:
        cml_meta = cml.coords.to_dataset()
        cml_meta = cml_meta.drop_vars("time")
        cml_df = cml_meta.to_dataframe().reset_index()
    else:
        cml_df = cml.to_dataframe()

    cml_df = cml_df.reset_index().drop_duplicates()

    v = pd.DataFrame({
        "x": cml_df.site_1_lon - cml_df.site_0_lon,
        "y": cml_df.site_1_lat - cml_df.site_0_lat,
    })
    phi_rad = np.deg2rad(cml_df.site_1_lat - cml_df.site_0_lat)
    v.x *= np.cos(phi_rad)


    n = pd.DataFrame({"x": -v.y, "y": v.x})
    norm = (1 / np.sqrt(n.x**2 + n.y**2)).values.reshape(-1, 1)
    n *= norm
    n.x /= np.cos(phi_rad)
    

    sblnk_rel_num = cml_df.groupby("cml_id").cumcount() + 2
    sign = (sblnk_rel_num % 2) * 2 - 1
    magnitude = offset * (sblnk_rel_num // 2) * sign

    s0_lns = cml_df.site_0_lon + magnitude * n.x
    s1_lns = cml_df.site_1_lon + magnitude * n.x
    s0_lts = cml_df.site_0_lat + magnitude * n.y
    s1_lts = cml_df.site_1_lat + magnitude * n.y

    geom = [LineString([(s0_ln, s0_lt), (s1_ln, s1_lt)]) for s0_ln, s1_ln, s0_lt, s1_lt  in zip(s0_lns, s1_lns, s0_lts, s1_lts)]
    return gpd.GeoDataFrame(cml_df, geometry=geom, crs="EPSG:4326")
