"""This module groups all the functions used to filter data based in other sensor data"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/05_data.filter.ipynb.

# %% auto #0
__all__ = ['filter_by_distance_to_nearest_gauge']

# %% ../../nbs/05_data.filter.ipynb #edeed455
import pandas as pd
import xarray as xr

from .merge import get_link_centers_opensense_v2, get_gauge_coords, haversine_distance

# %% ../../nbs/05_data.filter.ipynb #6c062e36
def filter_by_distance_to_nearest_gauge(
        cml: xr.Dataset, # CML dataset containing link information with coordinates
        gauges: xr.Dataset, # Dataset containing rain gauge locations
        mx_dist: float, # Maximum allowed distance (in km) from a link center to its nearest gauge. Links farther than this are filtered out.
        gauge_lat: str = "lat", # Name of the latitude coordinate in the gauges dataset
        gauge_lon: str = "lon" # Name of the longitude coordinate in the gauges dataset
    ) -> xr.Dataset: # Filtered CML dataset, containing only links whose center is within `mx_dist` km of at least one gauge
    """Filter CML links based on their distance to the nearest rain gauge."""
    link_centers = get_link_centers_opensense_v2(cml)
    gauge_coords = get_gauge_coords(gauges, lat=gauge_lat, lon=gauge_lon)
    
    in_range = [cml_id for cml_id, link in link_centers.iterrows() if gauge_coords.apply(haversine_distance, axis=1, point2=link).min() <= mx_dist]
    return cml.sel(cml_id=in_range)
