"""This module groups all the functions used to merge together different data sources such as CML, Gauges or Radar."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/05_data.merge.ipynb.

# %% auto 0
__all__ = ['assign_nearest_gauge_to_link_center']

# %% ../../nbs/05_data.merge.ipynb 2
import pandas as pd
import xarray as xr
from geopy.distance import geodesic

# %% ../../nbs/05_data.merge.ipynb 11
def get_link_centers_opensense_v2(cml: xr.Dataset) -> pd.DataFrame:
    """Get the center coordinates of each link in the CML dataset for the V2 of the OpenSense standard."""
    links = cml[["site_0_lat", "site_0_lon", "site_1_lat", "site_1_lon"]]
    links["center_lat"] = (links["site_0_lat"] + links["site_1_lat"]) / 2
    links["center_lon"] = (links["site_0_lon"] + links["site_1_lon"]) / 2
    links = links.to_dataframe()[list(links.data_vars)]
    return links.rename(columns={"center_lat": "lat", "center_lon": "lon"})

# %% ../../nbs/05_data.merge.ipynb 14
def get_gauge_coords(
        gauges: xr.Dataset, # Dataset containing gauges coordinates
        lat: str = "gauge_lat", # Name of the latitude coordinate in the dataset
        lon: str = "gauge_lon" # Name of the longitude coordinate in the dataset
    ) -> pd.DataFrame:
    """Get the coordinates of each gauge in the gauges dataset."""
    gauges_metadata = gauges[[lat, lon]].to_dataframe()
    gauges_coords = gauges_metadata[[lat, lon]].rename(columns={lat: "lat", lon: "lon"})
    return gauges_coords

# %% ../../nbs/05_data.merge.ipynb 16
def haversine_distance(point1: pd.Series, point2: pd.Series) -> float:
    """Calculate the great circle distance between two points on Earth."""
    return geodesic((point1["lat"], point1["lon"]), (point2["lat"], point2["lon"])).kilometers

# %% ../../nbs/05_data.merge.ipynb 23
def assign_nearest_gauge_to_link_center(
        cml: xr.Dataset, # CML dataset containing link information
        gauges: xr.Dataset, # Dataset containing gauges coordinates
        gauge_id: str = "gauge_name", # Name of the dimension of the gauge identifier in the gauges dataset
        gauge_lat: str = "gauge_lat", # Name of the latitude coordinate in the gauges dataset
        gauge_lon: str = "gauge_lon" # Name of the longitude coordinate in the gauges dataset
    ) -> xr.Dataset: # CML dataset merged with nearest gauge data and metadata
    """Assign the nearest gauge to each CML link based on geodesic distance from gauge to link center coordinates."""
    link_centers = get_link_centers_opensense_v2(cml)
    gauges_coords = get_gauge_coords(gauges)
    nearest_gauge = {cml_id: gauges_coords.apply(haversine_distance, axis=1, point2=ctr_coords).idxmin() for cml_id, ctr_coords in link_centers.iterrows()}
    nearest_gauge = pd.Series(nearest_gauge.values(), index=nearest_gauge.keys(), name=gauge_id)
    nearest_gauge.index.name = "cml_id"
    return xr.merge([cml, gauges.sel({gauge_id: nearest_gauge.to_xarray()})], join="outer")
    
