repos:
- repo: https://github.com/fastai/nbdev
  rev: 3.0.15
  hooks:
  - id: nbdev-clean
  - id: nbdev-export
- repo: local
  hooks:
  - id: clean-maps-notebook
    name: Clean notebooks with heavy visualizations as outputs 
    entry: nbdev-clean --fname nbs/21_maps.vector.ipynb --clear_all
    language: system
    pass_filenames: false
    always_run: true
