<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="This module groups all the functions and methods related to sample data that will be used to develop the raincell library.">

<title>Sample data – raincell</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-e85a36ed8f9e8f821a55ee8e73cfb0fa.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="styles.css">
<meta property="og:title" content="Sample data – raincell">
<meta property="og:description" content="This module groups all the functions and methods related to sample data that will be used to develop the raincell library.">
<meta property="og:site_name" content="raincell">
<meta name="twitter:title" content="Sample data – raincell">
<meta name="twitter:description" content="This module groups all the functions and methods related to sample data that will be used to develop the raincell library.">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-sidebar floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">raincell</span>
    </a>
  </div>
        <div class="quarto-navbar-tools tools-end">
</div>
          <div id="quarto-search" class="" title="Search"></div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./sample_data.html">Sample data</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">raincell</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sample_data.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Sample data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data.merge.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Merge multisensor data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./wetdry.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Wet/Dry classification</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./baseline.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Baseline</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./waa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Wet Antenna Attenuation (WAA)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rain_rate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Path Average Rain Rate Estimation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./plot.romulo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Romulo plot</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#get_cml_sample_fp" id="toc-get_cml_sample_fp" class="nav-link active" data-scroll-target="#get_cml_sample_fp">get_cml_sample_fp</a></li>
  <li><a href="#open_cml_sample" id="toc-open_cml_sample" class="nav-link" data-scroll-target="#open_cml_sample">open_cml_sample</a></li>
  <li><a href="#open_gauge_sample" id="toc-open_gauge_sample" class="nav-link" data-scroll-target="#open_gauge_sample">open_gauge_sample</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/rainsmore/raincell/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div><div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="sample_data.html.md"><i class="bi bi-file-code"></i>CommonMark</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Sample data</h1>
</div>

<div>
  <div class="description">
    This module groups all the functions and methods related to sample data that will be used to develop the raincell library.
  </div>
</div>


<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<!-- WARNING: THIS FILE WAS AUTOGENERATED! DO NOT EDIT! -->
<hr>
<p><a href="https://github.com/rainsmore/raincell/blob/main/raincell/sample.py#L14" target="_blank" style="float:right; font-size:smaller">source</a></p>
<section id="get_cml_sample_fp" class="level3">
<h3 class="anchored" data-anchor-id="get_cml_sample_fp">get_cml_sample_fp</h3>
<blockquote class="blockquote">
<pre><code> get_cml_sample_fp (processing_step:str)</code></pre>
</blockquote>
<hr>
<p><a href="https://github.com/rainsmore/raincell/blob/main/raincell/sample.py#L22" target="_blank" style="float:right; font-size:smaller">source</a></p>
</section>
<section id="open_cml_sample" class="level3">
<h3 class="anchored" data-anchor-id="open_cml_sample">open_cml_sample</h3>
<blockquote class="blockquote">
<pre><code> open_cml_sample (processing_step:str='raw')</code></pre>
</blockquote>
<p><em>Open Sample Commercial Microwave Link (CML) data at different processing steps.</em></p>
<div id="cell-4" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>open_cml_sample()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div><svg style="position: absolute; width: 0; height: 0; overflow: hidden">
<defs>
<symbol id="icon-database" viewbox="0 0 32 32">
<path d="M16 0c-8.837 0-16 2.239-16 5v4c0 2.761 7.163 5 16 5s16-2.239 16-5v-4c0-2.761-7.163-5-16-5z"></path>
<path d="M16 17c-8.837 0-16-2.239-16-5v6c0 2.761 7.163 5 16 5s16-2.239 16-5v-6c0 2.761-7.163 5-16 5z"></path>
<path d="M16 26c-8.837 0-16-2.239-16-5v6c0 2.761 7.163 5 16 5s16-2.239 16-5v-6c0 2.761-7.163 5-16 5z"></path>
</symbol>
<symbol id="icon-file-text2" viewbox="0 0 32 32">
<path d="M28.681 7.159c-0.694-0.947-1.662-2.053-2.724-3.116s-2.169-2.030-3.116-2.724c-1.612-1.182-2.393-1.319-2.841-1.319h-15.5c-1.378 0-2.5 1.121-2.5 2.5v27c0 1.378 1.122 2.5 2.5 2.5h23c1.378 0 2.5-1.122 2.5-2.5v-19.5c0-0.448-0.137-1.23-1.319-2.841zM24.543 5.457c0.959 0.959 1.712 1.825 2.268 2.543h-4.811v-4.811c0.718 0.556 1.584 1.309 2.543 2.268zM28 29.5c0 0.271-0.229 0.5-0.5 0.5h-23c-0.271 0-0.5-0.229-0.5-0.5v-27c0-0.271 0.229-0.5 0.5-0.5 0 0 15.499-0 15.5 0v7c0 0.552 0.448 1 1 1h7v19.5z"></path>
<path d="M23 26h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z"></path>
<path d="M23 22h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z"></path>
<path d="M23 18h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z"></path>
</symbol>
</defs>
</svg>
<style>/* CSS stylesheet for displaying xarray objects in notebooks */

:root {
  --xr-font-color0: var(
    --jp-content-font-color0,
    var(--pst-color-text-base rgba(0, 0, 0, 1))
  );
  --xr-font-color2: var(
    --jp-content-font-color2,
    var(--pst-color-text-base, rgba(0, 0, 0, 0.54))
  );
  --xr-font-color3: var(
    --jp-content-font-color3,
    var(--pst-color-text-base, rgba(0, 0, 0, 0.38))
  );
  --xr-border-color: var(
    --jp-border-color2,
    hsl(from var(--pst-color-on-background, white) h s calc(l - 10))
  );
  --xr-disabled-color: var(
    --jp-layout-color3,
    hsl(from var(--pst-color-on-background, white) h s calc(l - 40))
  );
  --xr-background-color: var(
    --jp-layout-color0,
    var(--pst-color-on-background, white)
  );
  --xr-background-color-row-even: var(
    --jp-layout-color1,
    hsl(from var(--pst-color-on-background, white) h s calc(l - 5))
  );
  --xr-background-color-row-odd: var(
    --jp-layout-color2,
    hsl(from var(--pst-color-on-background, white) h s calc(l - 15))
  );
}

html[theme="dark"],
html[data-theme="dark"],
body[data-theme="dark"],
body.vscode-dark {
  --xr-font-color0: var(
    --jp-content-font-color0,
    var(--pst-color-text-base, rgba(255, 255, 255, 1))
  );
  --xr-font-color2: var(
    --jp-content-font-color2,
    var(--pst-color-text-base, rgba(255, 255, 255, 0.54))
  );
  --xr-font-color3: var(
    --jp-content-font-color3,
    var(--pst-color-text-base, rgba(255, 255, 255, 0.38))
  );
  --xr-border-color: var(
    --jp-border-color2,
    hsl(from var(--pst-color-on-background, #111111) h s calc(l + 10))
  );
  --xr-disabled-color: var(
    --jp-layout-color3,
    hsl(from var(--pst-color-on-background, #111111) h s calc(l + 40))
  );
  --xr-background-color: var(
    --jp-layout-color0,
    var(--pst-color-on-background, #111111)
  );
  --xr-background-color-row-even: var(
    --jp-layout-color1,
    hsl(from var(--pst-color-on-background, #111111) h s calc(l + 5))
  );
  --xr-background-color-row-odd: var(
    --jp-layout-color2,
    hsl(from var(--pst-color-on-background, #111111) h s calc(l + 15))
  );
}

.xr-wrap {
  display: block !important;
  min-width: 300px;
  max-width: 700px;
  line-height: 1.6;
}

.xr-text-repr-fallback {
  /* fallback to plain text repr when CSS is not injected (untrusted notebook) */
  display: none;
}

.xr-header {
  padding-top: 6px;
  padding-bottom: 6px;
  margin-bottom: 4px;
  border-bottom: solid 1px var(--xr-border-color);
}

.xr-header > div,
.xr-header > ul {
  display: inline;
  margin-top: 0;
  margin-bottom: 0;
}

.xr-obj-type,
.xr-obj-name,
.xr-group-name {
  margin-left: 2px;
  margin-right: 10px;
}

.xr-group-name::before {
  content: "📁";
  padding-right: 0.3em;
}

.xr-group-name,
.xr-obj-type {
  color: var(--xr-font-color2);
}

.xr-sections {
  padding-left: 0 !important;
  display: grid;
  grid-template-columns: 150px auto auto 1fr 0 20px 0 20px;
  margin-block-start: 0;
  margin-block-end: 0;
}

.xr-section-item {
  display: contents;
}

.xr-section-item input {
  display: inline-block;
  opacity: 0;
  height: 0;
  margin: 0;
}

.xr-section-item input + label {
  color: var(--xr-disabled-color);
  border: 2px solid transparent !important;
}

.xr-section-item input:enabled + label {
  cursor: pointer;
  color: var(--xr-font-color2);
}

.xr-section-item input:focus + label {
  border: 2px solid var(--xr-font-color0) !important;
}

.xr-section-item input:enabled + label:hover {
  color: var(--xr-font-color0);
}

.xr-section-summary {
  grid-column: 1;
  color: var(--xr-font-color2);
  font-weight: 500;
}

.xr-section-summary > span {
  display: inline-block;
  padding-left: 0.5em;
}

.xr-section-summary-in:disabled + label {
  color: var(--xr-font-color2);
}

.xr-section-summary-in + label:before {
  display: inline-block;
  content: "►";
  font-size: 11px;
  width: 15px;
  text-align: center;
}

.xr-section-summary-in:disabled + label:before {
  color: var(--xr-disabled-color);
}

.xr-section-summary-in:checked + label:before {
  content: "▼";
}

.xr-section-summary-in:checked + label > span {
  display: none;
}

.xr-section-summary,
.xr-section-inline-details {
  padding-top: 4px;
}

.xr-section-inline-details {
  grid-column: 2 / -1;
}

.xr-section-details {
  display: none;
  grid-column: 1 / -1;
  margin-top: 4px;
  margin-bottom: 5px;
}

.xr-section-summary-in:checked ~ .xr-section-details {
  display: contents;
}

.xr-group-box {
  display: inline-grid;
  grid-template-columns: 0px 20px auto;
  width: 100%;
}

.xr-group-box-vline {
  grid-column-start: 1;
  border-right: 0.2em solid;
  border-color: var(--xr-border-color);
  width: 0px;
}

.xr-group-box-hline {
  grid-column-start: 2;
  grid-row-start: 1;
  height: 1em;
  width: 20px;
  border-bottom: 0.2em solid;
  border-color: var(--xr-border-color);
}

.xr-group-box-contents {
  grid-column-start: 3;
}

.xr-array-wrap {
  grid-column: 1 / -1;
  display: grid;
  grid-template-columns: 20px auto;
}

.xr-array-wrap > label {
  grid-column: 1;
  vertical-align: top;
}

.xr-preview {
  color: var(--xr-font-color3);
}

.xr-array-preview,
.xr-array-data {
  padding: 0 5px !important;
  grid-column: 2;
}

.xr-array-data,
.xr-array-in:checked ~ .xr-array-preview {
  display: none;
}

.xr-array-in:checked ~ .xr-array-data,
.xr-array-preview {
  display: inline-block;
}

.xr-dim-list {
  display: inline-block !important;
  list-style: none;
  padding: 0 !important;
  margin: 0;
}

.xr-dim-list li {
  display: inline-block;
  padding: 0;
  margin: 0;
}

.xr-dim-list:before {
  content: "(";
}

.xr-dim-list:after {
  content: ")";
}

.xr-dim-list li:not(:last-child):after {
  content: ",";
  padding-right: 5px;
}

.xr-has-index {
  font-weight: bold;
}

.xr-var-list,
.xr-var-item {
  display: contents;
}

.xr-var-item > div,
.xr-var-item label,
.xr-var-item > .xr-var-name span {
  background-color: var(--xr-background-color-row-even);
  border-color: var(--xr-background-color-row-odd);
  margin-bottom: 0;
  padding-top: 2px;
}

.xr-var-item > .xr-var-name:hover span {
  padding-right: 5px;
}

.xr-var-list > li:nth-child(odd) > div,
.xr-var-list > li:nth-child(odd) > label,
.xr-var-list > li:nth-child(odd) > .xr-var-name span {
  background-color: var(--xr-background-color-row-odd);
  border-color: var(--xr-background-color-row-even);
}

.xr-var-name {
  grid-column: 1;
}

.xr-var-dims {
  grid-column: 2;
}

.xr-var-dtype {
  grid-column: 3;
  text-align: right;
  color: var(--xr-font-color2);
}

.xr-var-preview {
  grid-column: 4;
}

.xr-index-preview {
  grid-column: 2 / 5;
  color: var(--xr-font-color2);
}

.xr-var-name,
.xr-var-dims,
.xr-var-dtype,
.xr-preview,
.xr-attrs dt {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  padding-right: 10px;
}

.xr-var-name:hover,
.xr-var-dims:hover,
.xr-var-dtype:hover,
.xr-attrs dt:hover {
  overflow: visible;
  width: auto;
  z-index: 1;
}

.xr-var-attrs,
.xr-var-data,
.xr-index-data {
  display: none;
  border-top: 2px dotted var(--xr-background-color);
  padding-bottom: 20px !important;
  padding-top: 10px !important;
}

.xr-var-attrs-in + label,
.xr-var-data-in + label,
.xr-index-data-in + label {
  padding: 0 1px;
}

.xr-var-attrs-in:checked ~ .xr-var-attrs,
.xr-var-data-in:checked ~ .xr-var-data,
.xr-index-data-in:checked ~ .xr-index-data {
  display: block;
}

.xr-var-data > table {
  float: right;
}

.xr-var-data > pre,
.xr-index-data > pre,
.xr-var-data > table > tbody > tr {
  background-color: transparent !important;
}

.xr-var-name span,
.xr-var-data,
.xr-index-name div,
.xr-index-data,
.xr-attrs {
  padding-left: 25px !important;
}

.xr-attrs,
.xr-var-attrs,
.xr-var-data,
.xr-index-data {
  grid-column: 1 / -1;
}

dl.xr-attrs {
  padding: 0;
  margin: 0;
  display: grid;
  grid-template-columns: 125px auto;
}

.xr-attrs dt,
.xr-attrs dd {
  padding: 0;
  margin: 0;
  float: left;
  padding-right: 10px;
  width: auto;
}

.xr-attrs dt {
  font-weight: normal;
  grid-column: 1;
}

.xr-attrs dt:hover span {
  display: inline-block;
  background: var(--xr-background-color);
  padding-right: 10px;
}

.xr-attrs dd {
  grid-column: 2;
  white-space: pre-wrap;
  word-break: break-all;
}

.xr-icon-database,
.xr-icon-file-text2,
.xr-no-icon {
  display: inline-block;
  vertical-align: middle;
  width: 1em;
  height: 1.5em !important;
  stroke-width: 0;
  stroke: currentColor;
  fill: currentColor;
}

.xr-var-attrs-in:checked + label > .xr-icon-file-text2,
.xr-var-data-in:checked + label > .xr-icon-database,
.xr-index-data-in:checked + label > .xr-icon-database {
  color: var(--xr-font-color0);
  filter: drop-shadow(1px 1px 5px var(--xr-font-color2));
  stroke-width: 0.8px;
}
</style><pre class="xr-text-repr-fallback">&lt;xarray.Dataset&gt; Size: 108MB
Dimensions:      (cml_id: 126, sublink_id: 6, time: 2964)
Coordinates:
  * cml_id       (cml_id) &lt;U19 10kB '3.984686N-9.789517E' ... '4.095631N-9.74...
  * sublink_id   (sublink_id) &lt;U3 72B '0_0' '0_1' '1_0' '1_1' '2_0' '2_1'
  * time         (time) datetime64[ns] 24kB 2019-07-01T00:05:00 ... 2019-07-3...
    frequency    (cml_id, sublink_id) float64 6kB 1.505e+04 1.456e+04 ... nan
    site_0_lat   (cml_id) float64 1kB 3.993 3.993 3.997 ... 4.087 4.092 4.094
    site_0_lon   (cml_id) float64 1kB 9.787 9.787 9.764 ... 9.766 9.729 9.742
    site_1_lat   (cml_id) float64 1kB 3.977 3.979 3.997 ... 4.095 4.091 4.097
    site_1_lon   (cml_id) float64 1kB 9.792 9.816 9.759 ... 9.764 9.736 9.743
    transmitter  (cml_id, sublink_id) float64 6kB 0.0 1.0 nan ... nan nan nan
    length       (cml_id) float64 1kB 1.852e+03 3.573e+03 556.0 ... 736.0 419.0
Data variables:
    rsl_avg      (cml_id, sublink_id, time) float64 18MB -48.0 -48.0 ... nan nan
    tsl_avg      (cml_id, sublink_id, time) float64 18MB 10.0 10.0 ... nan nan
    rsl_min      (cml_id, sublink_id, time) float64 18MB -48.8 -48.3 ... nan nan
    tsl_min      (cml_id, sublink_id, time) float64 18MB 10.0 10.0 ... nan nan
    rsl_max      (cml_id, sublink_id, time) float64 18MB -47.6 -47.8 ... nan nan
    tsl_max      (cml_id, sublink_id, time) float64 18MB 10.0 10.0 ... nan nan
Attributes:
    title:                 East side Douala CML links sample data
    file author(s):        Orange Cameroun and IRD Rainsmore Group
    institution:           Orange Cameroun and IRD Rainsmore Group
    date:                  2025-11-07
    source:                Modified Orange Cameroun CML data for example purp...
    naming convention:     COST ACTION OPENSENSE V2
    license restrictions:  CC BY-NC-ND 4.0</pre><div class="xr-wrap" style="display:none"><div class="xr-header"><div class="xr-obj-type">xarray.Dataset</div></div><ul class="xr-sections"><li class="xr-section-item"><input id="section-714a94b3-1268-4944-b7b7-25f73c4fd43f" class="xr-section-summary-in" type="checkbox" disabled=""><label for="section-714a94b3-1268-4944-b7b7-25f73c4fd43f" class="xr-section-summary" title="Expand/collapse section">Dimensions:</label><div class="xr-section-inline-details"><ul class="xr-dim-list"><li><span class="xr-has-index">cml_id</span>: 126</li><li><span class="xr-has-index">sublink_id</span>: 6</li><li><span class="xr-has-index">time</span>: 2964</li></ul></div><div class="xr-section-details"></div></li><li class="xr-section-item"><input id="section-48a66cc0-b923-4247-a597-daff4ab4e9da" class="xr-section-summary-in" type="checkbox" checked=""><label for="section-48a66cc0-b923-4247-a597-daff4ab4e9da" class="xr-section-summary">Coordinates: <span>(10)</span></label><div class="xr-section-inline-details"></div><div class="xr-section-details"><ul class="xr-var-list"><li class="xr-var-item"><div class="xr-var-name"><span class="xr-has-index">cml_id</span></div><div class="xr-var-dims">(cml_id)</div><div class="xr-var-dtype">&lt;U19</div><div class="xr-var-preview xr-preview">'3.984686N-9.789517E' ... '4.095...</div><input id="attrs-95140134-1d86-4d41-a8aa-a5ad19bd6b19" class="xr-var-attrs-in" type="checkbox"><label for="attrs-95140134-1d86-4d41-a8aa-a5ad19bd6b19" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-334a6ca4-cece-4187-a54e-0332f7c71452" class="xr-var-data-in" type="checkbox"><label for="data-334a6ca4-cece-4187-a54e-0332f7c71452" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>commercial_microwave_link_identifier</dd></dl></div><div class="xr-var-data"><pre>array(['3.984686N-9.789517E', '3.985691N-9.801648E', '3.996996N-9.761328E',
       '4.002892N-9.746861E', '4.007006N-9.767519E', '4.008236N-9.788792E',
       '4.013028N-9.703569E', '4.013180N-9.765819E', '4.014916N-9.732514E',
       '4.015776N-9.756458E', '4.016656N-9.736544E', '4.016736N-9.764944E',
       '4.016944N-9.753305E', '4.016962N-9.726686E', '4.017736N-9.748042E',
       '4.018721N-9.762325E', '4.018764N-9.746583E', '4.019750N-9.767776E',
       '4.019930N-9.759403E', '4.020440N-9.708914E', '4.021256N-9.746180E',
       '4.021528N-9.798792E', '4.024043N-9.680260E', '4.024381N-9.733274E',
       '4.024750N-9.697977E', '4.025125N-9.770912E', '4.025270N-9.739593E',
       '4.025625N-9.735889E', '4.025880N-9.703252E', '4.026149N-9.695650E',
       '4.028700N-9.729934E', '4.028708N-9.703542E', '4.029412N-9.691581E',
       '4.030556N-9.705569E', '4.030907N-9.694160E', '4.031399N-9.698080E',
       '4.032132N-9.730055E', '4.032560N-9.713835E', '4.033181N-9.761500E',
       '4.033883N-9.691732E', '4.034149N-9.772296E', '4.034701N-9.729347E',
       '4.035134N-9.697875E', '4.035679N-9.685969E', '4.037778N-9.767028E',
       '4.038505N-9.704950E', '4.039270N-9.722472E', '4.039580N-9.737019E',
       '4.040098N-9.700828E', '4.040792N-9.776750E', '4.041057N-9.688122E',
       '4.041068N-9.758319E', '4.041256N-9.730708E', '4.041347N-9.773597E',
       '4.042298N-9.740333E', '4.042502N-9.716614E', '4.042568N-9.698128E',
       '4.042817N-9.705986E', '4.043833N-9.687306E', '4.043927N-9.704314E',
       '4.044597N-9.727069E', '4.044736N-9.710024E', '4.047503N-9.718511E',
       '4.048013N-9.705195E', '4.048153N-9.698625E', '4.048916N-9.707667E',
       '4.049925N-9.774582E', '4.050150N-9.740475E', '4.050347N-9.703473E',
       '4.050528N-9.753875E', '4.052083N-9.788583E', '4.054458N-9.763403E',
       '4.055917N-9.752681E', '4.056070N-9.768000E', '4.056121N-9.742152E',
       '4.056639N-9.747222E', '4.056847N-9.738556E', '4.056959N-9.742472E',
       '4.057459N-9.765805E', '4.058236N-9.768889E', '4.058746N-9.717759E',
       '4.058868N-9.752014E', '4.059014N-9.759348E', '4.059486N-9.711928E',
       '4.059995N-9.755237E', '4.060816N-9.773042E', '4.061585N-9.744609E',
       '4.062778N-9.705333E', '4.062903N-9.717026E', '4.064425N-9.761904E',
       '4.065399N-9.711476E', '4.066549N-9.795621E', '4.067820N-9.720067E',
       '4.068528N-9.726056E', '4.069079N-9.713870E', '4.071390N-9.727304E',
       '4.072442N-9.739396E', '4.072503N-9.771625E', '4.074162N-9.717861E',
       '4.074764N-9.753625E', '4.075098N-9.719528E', '4.075836N-9.783931E',
       '4.076554N-9.759058E', '4.078069N-9.720598E', '4.078309N-9.751204E',
       '4.079211N-9.793847E', '4.079299N-9.747812E', '4.079652N-9.763472E',
       '4.080070N-9.789737E', '4.080399N-9.753111E', '4.081654N-9.761180E',
       '4.082815N-9.790491E', '4.083040N-9.782281E', '4.083986N-9.756718E',
       '4.084496N-9.740917E', '4.084732N-9.745625E', '4.085795N-9.784833E',
       '4.086056N-9.752500E', '4.086283N-9.759477E', '4.086545N-9.797375E',
       '4.088385N-9.755778E', '4.089034N-9.734926E', '4.089819N-9.752833E',
       '4.090565N-9.765189E', '4.091611N-9.732743E', '4.095631N-9.742507E'],
      dtype='&lt;U19')</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span class="xr-has-index">sublink_id</span></div><div class="xr-var-dims">(sublink_id)</div><div class="xr-var-dtype">&lt;U3</div><div class="xr-var-preview xr-preview">'0_0' '0_1' '1_0' '1_1' '2_0' '2_1'</div><input id="attrs-417cffd7-9496-491b-9023-16f82fb0431f" class="xr-var-attrs-in" type="checkbox"><label for="attrs-417cffd7-9496-491b-9023-16f82fb0431f" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-bc0c4852-d310-4c2b-9e43-73a09f1b22b4" class="xr-var-data-in" type="checkbox"><label for="data-bc0c4852-d310-4c2b-9e43-73a09f1b22b4" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>sublink_identifier</dd></dl></div><div class="xr-var-data"><pre>array(['0_0', '0_1', '1_0', '1_1', '2_0', '2_1'], dtype='&lt;U3')</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span class="xr-has-index">time</span></div><div class="xr-var-dims">(time)</div><div class="xr-var-dtype">datetime64[ns]</div><div class="xr-var-preview xr-preview">2019-07-01T00:05:00 ... 2019-07-...</div><input id="attrs-5b0458ef-0335-477e-b97a-8790f7bceb81" class="xr-var-attrs-in" type="checkbox"><label for="attrs-5b0458ef-0335-477e-b97a-8790f7bceb81" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-5d8b0b59-1f1a-4afa-bee0-480e350b6d58" class="xr-var-data-in" type="checkbox"><label for="data-5d8b0b59-1f1a-4afa-bee0-480e350b6d58" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>time_utc</dd></dl></div><div class="xr-var-data"><pre>array(['2019-07-01T00:05:00.000000000', '2019-07-01T00:20:00.000000000',
       '2019-07-01T00:35:00.000000000', ..., '2019-07-31T23:20:00.000000000',
       '2019-07-31T23:35:00.000000000', '2019-07-31T23:50:00.000000000'],
      shape=(2964,), dtype='datetime64[ns]')</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>frequency</span></div><div class="xr-var-dims">(cml_id, sublink_id)</div><div class="xr-var-dtype">float64</div><div class="xr-var-preview xr-preview">1.505e+04 1.456e+04 nan ... nan nan</div><input id="attrs-e81d1955-3875-43b6-bd9c-d401fb0d9def" class="xr-var-attrs-in" type="checkbox"><label for="attrs-e81d1955-3875-43b6-bd9c-d401fb0d9def" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-a101353c-8aba-4ff0-9429-73ca1da70d4c" class="xr-var-data-in" type="checkbox"><label for="data-a101353c-8aba-4ff0-9429-73ca1da70d4c" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>units :</span></dt><dd>MHz</dd><dt><span>long_name :</span></dt><dd>sublink_frequency</dd></dl></div><div class="xr-var-data"><pre>array([[15047., 14557.,    nan,    nan,    nan,    nan],
       [12765., 13031.,    nan,    nan,    nan,    nan],
       [18765., 17755.,    nan,    nan,    nan,    nan],
       [14907., 14417.,    nan,    nan,    nan,    nan],
       [17728., 18738.,    nan,    nan,    nan,    nan],
       [14417., 14907.,    nan,    nan,    nan,    nan],
       [14935., 14445.,    nan,    nan,    nan,    nan],
       [14529., 15019.,    nan,    nan,    nan,    nan],
       [14935., 14445.,    nan,    nan,    nan,    nan],
       [14473., 14963.,    nan,    nan,    nan,    nan],
       [17755., 18765.,    nan,    nan,    nan,    nan],
       [ 8335.,  8454.,    nan,    nan,    nan,    nan],
       [14935., 14445.,    nan,    nan,    nan,    nan],
       [15019., 14529.,    nan,    nan,    nan,    nan],
       [14991., 14501.,    nan,    nan,    nan,    nan],
       [14501., 14991.,    nan,    nan,    nan,    nan],
       [14557., 15047.,    nan,    nan,    nan,    nan],
       [14557., 15047.,    nan,    nan,    nan,    nan],
       [15103., 14613.,    nan,    nan,    nan,    nan],
       [14417., 14907.,    nan,    nan,    nan,    nan],
...
       [14445., 14935.,    nan,    nan,    nan,    nan],
       [14529., 15019.,    nan,    nan,    nan,    nan],
       [17838., 18848.,    nan,    nan,    nan,    nan],
       [ 8468.,  8349.,    nan,    nan,    nan,    nan],
       [14417., 14907.,    nan,    nan,    nan,    nan],
       [14935., 14445.,    nan,    nan,    nan,    nan],
       [14991., 14501.,    nan,    nan,    nan,    nan],
       [14417., 14907.,    nan,    nan,    nan,    nan],
       [ 8426.,  8307.,    nan,    nan,    nan,    nan],
       [14557., 15047.,    nan,    nan,    nan,    nan],
       [14963., 14473.,    nan,    nan,    nan,    nan],
       [ 8468.,  8349.,    nan,    nan,    nan,    nan],
       [14557., 15047.,    nan,    nan,    nan,    nan],
       [14991., 14501.,    nan,    nan,    nan,    nan],
       [14585., 15075.,    nan,    nan,    nan,    nan],
       [17728., 18738.,    nan,    nan,    nan,    nan],
       [14529., 15019.,    nan,    nan,    nan,    nan],
       [14991., 14501.,    nan,    nan,    nan,    nan],
       [14585., 15075.,    nan,    nan,    nan,    nan],
       [14501., 14991.,    nan,    nan,    nan,    nan]])</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>site_0_lat</span></div><div class="xr-var-dims">(cml_id)</div><div class="xr-var-dtype">float64</div><div class="xr-var-preview xr-preview">3.993 3.993 3.997 ... 4.092 4.094</div><input id="attrs-fe811ffb-22a3-4052-b567-f8a58e44000f" class="xr-var-attrs-in" type="checkbox"><label for="attrs-fe811ffb-22a3-4052-b567-f8a58e44000f" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-238bac48-d89f-409d-ab94-b2e02be6b1c0" class="xr-var-data-in" type="checkbox"><label for="data-238bac48-d89f-409d-ab94-b2e02be6b1c0" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>units :</span></dt><dd>degrees_in_WGS84_projection</dd><dt><span>long_name :</span></dt><dd>site_0_latitude</dd></dl></div><div class="xr-var-data"><pre>array([3.992722, 3.992722, 3.997361, 4.002553, 4.003512, 4.004194,
       4.01775 , 4.029   , 4.009639, 4.029   , 4.015972, 4.029   ,
       4.015972, 4.023444, 4.015972, 4.029   , 4.014417, 4.029   ,
       4.015972, 4.029381, 4.0194  , 4.023167, 4.022056, 4.015972,
       4.029381, 4.029   , 4.022139, 4.015972, 4.029381, 4.029381,
       4.040819, 4.029083, 4.029381, 4.029083, 4.029381, 4.029381,
       4.040819, 4.032   , 4.029   , 4.032433, 4.033028, 4.040819,
       4.029381, 4.033886, 4.029   , 4.040083, 4.040819, 4.040819,
       4.040886, 4.042306, 4.041417, 4.03875 , 4.040819, 4.029   ,
       4.040819, 4.056559, 4.040886, 4.04244 , 4.041417, 4.043194,
       4.041694, 4.040886, 4.04642 , 4.044694, 4.049556, 4.051333,
       4.050192, 4.052028, 4.052444, 4.053667, 4.053694, 4.053667,
       4.053667, 4.0585  , 4.058056, 4.053667, 4.060028, 4.053667,
       4.0585  , 4.053667, 4.06425 , 4.053667, 4.053667, 4.060333,
       4.053667, 4.0585  , 4.059611, 4.059583, 4.06425 , 4.066322,
       4.063917, 4.065848, 4.06425 , 4.065667, 4.071278, 4.071389,
       4.072222, 4.071639, 4.06425 , 4.074778, 4.070306, 4.0817  ,
       4.074778, 4.079889, 4.081867, 4.0817  , 4.085936, 4.085936,
       4.0817  , 4.085936, 4.081441, 4.0817  , 4.0817  , 4.074778,
       4.085936, 4.085936, 4.0817  , 4.074778, 4.085936, 4.0817  ,
       4.085936, 4.08679 , 4.074778, 4.08663 , 4.091944, 4.09393 ])</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>site_0_lon</span></div><div class="xr-var-dims">(cml_id)</div><div class="xr-var-dtype">float64</div><div class="xr-var-preview xr-preview">9.787 9.787 9.764 ... 9.729 9.742</div><input id="attrs-d2c55674-faad-4f5d-9f87-60b699df0544" class="xr-var-attrs-in" type="checkbox"><label for="attrs-d2c55674-faad-4f5d-9f87-60b699df0544" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-4c671f31-c88b-45db-8aea-7531d3807185" class="xr-var-data-in" type="checkbox"><label for="data-4c671f31-c88b-45db-8aea-7531d3807185" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>units :</span></dt><dd>degrees_in_WGS84_projection</dd><dt><span>long_name :</span></dt><dd>site_0_longitude</dd></dl></div><div class="xr-var-data"><pre>array([9.787167, 9.787167, 9.763806, 9.745083, 9.76732 , 9.799472,
       9.705944, 9.767833, 9.741417, 9.767833, 9.738528, 9.767833,
       9.738528, 9.727083, 9.738528, 9.767833, 9.744694, 9.767833,
       9.738528, 9.696744, 9.743889, 9.792   , 9.67025 , 9.738528,
       9.696744, 9.767833, 9.737194, 9.738528, 9.696744, 9.696744,
       9.733028, 9.701944, 9.696744, 9.701944, 9.696744, 9.696744,
       9.733028, 9.71564 , 9.767833, 9.691575, 9.774333, 9.733028,
       9.696744, 9.683883, 9.767833, 9.706106, 9.733028, 9.733028,
       9.699006, 9.774   , 9.686417, 9.762056, 9.733028, 9.767833,
       9.733028, 9.702978, 9.699006, 9.704083, 9.686417, 9.707889,
       9.728389, 9.699006, 9.71598 , 9.703528, 9.698333, 9.706861,
       9.771911, 9.741306, 9.702389, 9.750917, 9.779361, 9.750917,
       9.750917, 9.768444, 9.738694, 9.750917, 9.726194, 9.750917,
       9.768444, 9.750917, 9.714664, 9.750917, 9.750917, 9.708444,
       9.750917, 9.768444, 9.743528, 9.704333, 9.714664, 9.759558,
       9.710083, 9.79152 , 9.714664, 9.722972, 9.714869, 9.729139,
       9.736111, 9.76925 , 9.714664, 9.761667, 9.719639, 9.786083,
       9.761667, 9.719417, 9.756825, 9.786083, 9.752944, 9.752944,
       9.786083, 9.752944, 9.765535, 9.786083, 9.786083, 9.761667,
       9.752944, 9.752944, 9.786083, 9.761667, 9.752944, 9.786083,
       9.752944, 9.73381 , 9.761667, 9.76601 , 9.729444, 9.74168 ])</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>site_1_lat</span></div><div class="xr-var-dims">(cml_id)</div><div class="xr-var-dtype">float64</div><div class="xr-var-preview xr-preview">3.977 3.979 3.997 ... 4.091 4.097</div><input id="attrs-b48411f9-40a8-4d41-8368-d7905f29a01c" class="xr-var-attrs-in" type="checkbox"><label for="attrs-b48411f9-40a8-4d41-8368-d7905f29a01c" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-b354cc3d-314a-465c-9e93-93aec8b9aeac" class="xr-var-data-in" type="checkbox"><label for="data-b354cc3d-314a-465c-9e93-93aec8b9aeac" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>units :</span></dt><dd>degrees in WGS84 projection</dd><dt><span>long_name :</span></dt><dd>site_1_latitude</dd></dl></div><div class="xr-var-data"><pre>array([3.97665 , 3.97866 , 3.99663 , 4.003231, 4.0105  , 4.012278,
       4.008306, 3.997361, 4.020194, 4.002553, 4.01734 , 4.004472,
       4.017917, 4.01048 , 4.0195  , 4.008442, 4.023111, 4.0105  ,
       4.023889, 4.0115  , 4.023111, 4.019889, 4.02603 , 4.03279 ,
       4.02012 , 4.02125 , 4.0284  , 4.035278, 4.02238 , 4.022917,
       4.01658 , 4.028333, 4.029444, 4.032028, 4.032433, 4.033417,
       4.023444, 4.03312 , 4.037361, 4.035333, 4.03527 , 4.028583,
       4.040886, 4.037472, 4.046556, 4.036926, 4.037722, 4.038342,
       4.03931 , 4.039278, 4.040697, 4.043386, 4.041694, 4.053694,
       4.043778, 4.028444, 4.04425 , 4.043194, 4.04625 , 4.044661,
       4.0475  , 4.048586, 4.048586, 4.051333, 4.04675 , 4.0465  ,
       4.049658, 4.048272, 4.04825 , 4.047389, 4.050472, 4.05525 ,
       4.058167, 4.053639, 4.054186, 4.059611, 4.053667, 4.06025 ,
       4.056417, 4.062806, 4.053242, 4.064069, 4.064361, 4.058638,
       4.066322, 4.063131, 4.06356 , 4.065972, 4.061556, 4.062528,
       4.06688 , 4.06725 , 4.07139 , 4.071389, 4.06688 , 4.07139 ,
       4.072661, 4.073367, 4.084075, 4.07475 , 4.079889, 4.069972,
       4.07833 , 4.07625 , 4.07475 , 4.076722, 4.072661, 4.073367,
       4.07844 , 4.074861, 4.081867, 4.08393 , 4.08438 , 4.093194,
       4.083056, 4.083528, 4.089889, 4.097333, 4.08663 , 4.091389,
       4.090833, 4.091278, 4.104861, 4.0945  , 4.091278, 4.097333])</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>site_1_lon</span></div><div class="xr-var-dims">(cml_id)</div><div class="xr-var-dtype">float64</div><div class="xr-var-preview xr-preview">9.792 9.816 9.759 ... 9.736 9.743</div><input id="attrs-dc01d537-6bf0-498b-bdd0-d73f8d9a4216" class="xr-var-attrs-in" type="checkbox"><label for="attrs-dc01d537-6bf0-498b-bdd0-d73f8d9a4216" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-65e2cf2c-fe9f-40d0-a936-e74d51bc387a" class="xr-var-data-in" type="checkbox"><label for="data-65e2cf2c-fe9f-40d0-a936-e74d51bc387a" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>units :</span></dt><dd>degrees in WGS84 projection</dd><dt><span>long_name :</span></dt><dd>site_1_longitude</dd></dl></div><div class="xr-var-data"><pre>array([9.791866, 9.81613 , 9.75885 , 9.748639, 9.767719, 9.778111,
       9.701194, 9.763806, 9.723611, 9.745083, 9.73456 , 9.762056,
       9.768083, 9.72629 , 9.757556, 9.756817, 9.748472, 9.767719,
       9.780278, 9.721083, 9.748472, 9.805583, 9.69027 , 9.72802 ,
       9.69921 , 9.77399 , 9.741992, 9.73325 , 9.70976 , 9.694556,
       9.72684 , 9.705139, 9.686417, 9.709194, 9.691575, 9.699417,
       9.727083, 9.71203 , 9.755167, 9.691889, 9.77026 , 9.725667,
       9.699006, 9.688056, 9.766222, 9.703794, 9.711917, 9.741011,
       9.70265 , 9.7795  , 9.689827, 9.754583, 9.728389, 9.779361,
       9.747639, 9.73025 , 9.69725 , 9.707889, 9.688194, 9.700739,
       9.72575 , 9.721043, 9.721043, 9.706861, 9.698917, 9.708472,
       9.777253, 9.739644, 9.704556, 9.756833, 9.797806, 9.775889,
       9.754444, 9.767556, 9.745611, 9.743528, 9.750917, 9.734028,
       9.763167, 9.786861, 9.720853, 9.75311 , 9.767778, 9.715412,
       9.759558, 9.777639, 9.74569 , 9.706333, 9.719389, 9.76425 ,
       9.71287 , 9.799722, 9.72547 , 9.729139, 9.71287 , 9.72547 ,
       9.742681, 9.774   , 9.721058, 9.745583, 9.719417, 9.781778,
       9.75645 , 9.721778, 9.745583, 9.801611, 9.742681, 9.774   ,
       9.79339 , 9.753278, 9.756825, 9.7949  , 9.77848 , 9.751769,
       9.728889, 9.738306, 9.783583, 9.743333, 9.76601 , 9.808667,
       9.758611, 9.736042, 9.744   , 9.764367, 9.736042, 9.743333])</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>transmitter</span></div><div class="xr-var-dims">(cml_id, sublink_id)</div><div class="xr-var-dtype">float64</div><div class="xr-var-preview xr-preview">0.0 1.0 nan nan ... nan nan nan nan</div><input id="attrs-e741a199-6fc0-4ed7-9d82-a7b5fcbb05c7" class="xr-var-attrs-in" type="checkbox"><label for="attrs-e741a199-6fc0-4ed7-9d82-a7b5fcbb05c7" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-ef5cf302-8703-4ae2-ab32-c470bc370638" class="xr-var-data-in" type="checkbox"><label for="data-ef5cf302-8703-4ae2-ab32-c470bc370638" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>transmitter_site_identifier</dd></dl></div><div class="xr-var-data"><pre>array([[ 0.,  1., nan, nan, nan, nan],
       [ 0.,  1., nan, nan, nan, nan],
       [ 0.,  1., nan, nan, nan, nan],
       [ 0.,  1., nan, nan, nan, nan],
       [ 0.,  1., nan, nan, nan, nan],
       [ 0.,  1., nan, nan, nan, nan],
       [ 0.,  1., nan, nan, nan, nan],
       [ 0.,  1., nan, nan, nan, nan],
       [ 0.,  1., nan, nan, nan, nan],
       [ 0.,  1., nan, nan, nan, nan],
       [ 0.,  1., nan, nan, nan, nan],
       [ 0.,  1., nan, nan, nan, nan],
       [ 0.,  1., nan, nan, nan, nan],
       [ 0.,  1., nan, nan, nan, nan],
       [ 0.,  1., nan, nan, nan, nan],
       [ 0.,  1., nan, nan, nan, nan],
       [ 0.,  1., nan, nan, nan, nan],
       [ 0.,  1., nan, nan, nan, nan],
       [ 0.,  1., nan, nan, nan, nan],
       [ 0.,  1., nan, nan, nan, nan],
...
       [ 0.,  1., nan, nan, nan, nan],
       [ 0.,  1., nan, nan, nan, nan],
       [ 0.,  1., nan, nan, nan, nan],
       [ 0.,  1., nan, nan, nan, nan],
       [ 0.,  1., nan, nan, nan, nan],
       [ 0.,  1., nan, nan, nan, nan],
       [ 0.,  1., nan, nan, nan, nan],
       [ 0.,  1., nan, nan, nan, nan],
       [ 0.,  1., nan, nan, nan, nan],
       [ 0.,  1., nan, nan, nan, nan],
       [ 0.,  1., nan, nan, nan, nan],
       [ 0.,  1., nan, nan, nan, nan],
       [ 0.,  1., nan, nan, nan, nan],
       [ 0.,  1., nan, nan, nan, nan],
       [ 0.,  1., nan, nan, nan, nan],
       [ 0.,  1., nan, nan, nan, nan],
       [ 0.,  1., nan, nan, nan, nan],
       [ 0.,  1., nan, nan, nan, nan],
       [ 0.,  1., nan, nan, nan, nan],
       [ 0.,  1., nan, nan, nan, nan]])</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>length</span></div><div class="xr-var-dims">(cml_id)</div><div class="xr-var-dtype">float64</div><div class="xr-var-preview xr-preview">1.852e+03 3.573e+03 ... 736.0 419.0</div><input id="attrs-ef03ed6a-daa2-401e-9e46-7376db42ec6a" class="xr-var-attrs-in" type="checkbox"><label for="attrs-ef03ed6a-daa2-401e-9e46-7376db42ec6a" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-e67edaf3-c90f-45e0-9131-6216830a1c4b" class="xr-var-data-in" type="checkbox"><label for="data-e67edaf3-c90f-45e0-9131-6216830a1c4b" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>units :</span></dt><dd>m</dd><dt><span>long_name :</span></dt><dd>distance_between_pair_of_antennas</dd></dl></div><div class="xr-var-data"><pre>array([1852., 3573.,  556.,  402.,  774., 2535., 1170., 3527., 2296.,
       3865.,  466., 2787., 3289., 1436., 2149., 2582., 1049., 2046.,
       4718., 3349.,  654., 1551., 2266., 2195., 1060., 1096.,  874.,
       2214., 1640.,  755., 2767.,  364., 1147.,  868.,  666.,  536.,
       2032.,  420., 1683.,  323.,  516., 1581., 1297.,  610., 1950.,
        433., 2369.,  928.,  441.,  697.,  387.,  975.,  524., 3016.,
       1655., 4340.,  420.,  431.,  570.,  810.,  706., 2591.,  611.,
        822.,  317.,  564.,  596.,  454.,  522.,  956., 2079., 2778.,
        633.,  546.,  879., 1051., 2834., 2012.,  630., 4117., 1398.,
       1176., 2214.,  796., 1697., 1142.,  498.,  741.,  603.,  669.,
        451.,  924., 1436.,  932.,  535.,  407.,  731.,  561., 2304.,
       1786., 1060., 1382.,  700.,  480., 1476., 1810., 1858., 2720.,
        888., 1225.,  968., 1010.,  895., 2314., 2690., 1647.,  947.,
       3219., 1453., 2727.,  830.,  555., 3862.,  889.,  736.,  419.])</pre></div></li></ul></div></li><li class="xr-section-item"><input id="section-6dff6c56-4412-4418-b756-f512b4197654" class="xr-section-summary-in" type="checkbox" checked=""><label for="section-6dff6c56-4412-4418-b756-f512b4197654" class="xr-section-summary">Data variables: <span>(6)</span></label><div class="xr-section-inline-details"></div><div class="xr-section-details"><ul class="xr-var-list"><li class="xr-var-item"><div class="xr-var-name"><span>rsl_avg</span></div><div class="xr-var-dims">(cml_id, sublink_id, time)</div><div class="xr-var-dtype">float64</div><div class="xr-var-preview xr-preview">-48.0 -48.0 -48.1 ... nan nan nan</div><input id="attrs-d853fcdc-8e95-471a-bd6d-724c6a74626e" class="xr-var-attrs-in" type="checkbox"><label for="attrs-d853fcdc-8e95-471a-bd6d-724c6a74626e" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-9da63a11-a512-44e0-84d8-5691cc2ffe93" class="xr-var-data-in" type="checkbox"><label for="data-9da63a11-a512-44e0-84d8-5691cc2ffe93" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>units :</span></dt><dd>dBm</dd><dt><span>long_name :</span></dt><dd>averaged_received_signal_level_over_time_window</dd></dl></div><div class="xr-var-data"><pre>array([[[-48. , -48. , -48.1, ..., -48.1, -48.1, -48.1],
        [-46.5, -46.6, -46.4, ..., -46.4, -46.4, -46.4],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan]],

       [[-43.6, -43.6, -43.7, ..., -40.6, -40.6, -40.6],
        [-43.9, -44.1, -44.1, ..., -95.9, -95.9, -95.9],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan]],

       [[-38.5, -38.5, -38.5, ..., -38.6, -38.6, -38.6],
        [-37.8, -37.8, -37.7, ..., -37.8, -37.8, -37.8],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan]],
...
        [-41.6, -41.5, -41.5, ..., -41.6, -41.6, -41.6],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan]],

       [[-52.9, -52.9, -52.9, ..., -53.4, -53.4, -53.3],
        [-52.8, -52.8, -52.8, ..., -53.3, -53.3, -53.2],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan]],

       [[-45.9, -45.9, -45.9, ..., -46.5, -46.4, -46.4],
        [-45.5, -45.5, -45.6, ..., -46.2, -46.2, -46.1],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan]]],
      shape=(126, 6, 2964))</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>tsl_avg</span></div><div class="xr-var-dims">(cml_id, sublink_id, time)</div><div class="xr-var-dtype">float64</div><div class="xr-var-preview xr-preview">10.0 10.0 10.0 10.0 ... nan nan nan</div><input id="attrs-5a90e043-432d-45d0-a8f6-86c872a9627d" class="xr-var-attrs-in" type="checkbox"><label for="attrs-5a90e043-432d-45d0-a8f6-86c872a9627d" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-5b402d19-d220-4d33-b907-df662509f7c3" class="xr-var-data-in" type="checkbox"><label for="data-5b402d19-d220-4d33-b907-df662509f7c3" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>units :</span></dt><dd>dBm</dd><dt><span>long_name :</span></dt><dd>averaged_transmitted_signal_level_over_time_window</dd></dl></div><div class="xr-var-data"><pre>array([[[10., 10., 10., ..., 10., 10., 10.],
        [10., 10., 10., ..., 10., 10., 10.],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[19., 19., 19., ..., 19., 19., 19.],
        [19., 19., 19., ..., 19., 19., 19.],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[ 8.,  8.,  8., ...,  8.,  8.,  8.],
        [ 8.,  8.,  8., ...,  8.,  8.,  8.],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],
...
       [[ 8.,  8.,  8., ...,  8.,  8.,  8.],
        [ 8.,  8.,  8., ...,  8.,  8.,  8.],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[ 1.,  1.,  1., ...,  1.,  1.,  1.],
        [ 1.,  1.,  1., ...,  1.,  1.,  1.],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[ 1.,  1.,  1., ...,  1.,  1.,  1.],
        [ 1.,  1.,  1., ...,  1.,  1.,  1.],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]], shape=(126, 6, 2964))</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>rsl_min</span></div><div class="xr-var-dims">(cml_id, sublink_id, time)</div><div class="xr-var-dtype">float64</div><div class="xr-var-preview xr-preview">-48.8 -48.3 -48.3 ... nan nan nan</div><input id="attrs-deb1d37a-d0d3-4a2c-b5aa-1882ba29c98d" class="xr-var-attrs-in" type="checkbox"><label for="attrs-deb1d37a-d0d3-4a2c-b5aa-1882ba29c98d" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-cc4a9016-bf31-4456-bafb-f8fe49e99260" class="xr-var-data-in" type="checkbox"><label for="data-cc4a9016-bf31-4456-bafb-f8fe49e99260" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>units :</span></dt><dd>dBm</dd><dt><span>long_name :</span></dt><dd>minimum_received_signal_level_over_time_window</dd></dl></div><div class="xr-var-data"><pre>array([[[-48.8, -48.3, -48.3, ..., -48.3, -48.3, -48.3],
        [-47.2, -46.8, -46.7, ..., -46.7, -46.5, -46.7],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan]],

       [[-43.8, -44.1, -44.2, ..., -41.8, -41.8, -41.8],
        [-44.9, -44.7, -44.7, ..., -95.9, -95.9, -95.9],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan]],

       [[-38.6, -38.6, -38.7, ..., -39. , -38.8, -38.8],
        [-37.9, -37.9, -37.8, ..., -38.2, -37.9, -37.9],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan]],
...
        [-41.7, -41.6, -41.6, ..., -41.7, -41.7, -41.7],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan]],

       [[-53. , -53. , -53. , ..., -53.6, -53.6, -53.5],
        [-52.9, -52.9, -52.9, ..., -53.6, -53.6, -53.3],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan]],

       [[-46. , -46. , -46. , ..., -46.8, -46.7, -46.7],
        [-45.6, -45.6, -45.6, ..., -46.4, -46.4, -46.3],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan]]],
      shape=(126, 6, 2964))</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>tsl_min</span></div><div class="xr-var-dims">(cml_id, sublink_id, time)</div><div class="xr-var-dtype">float64</div><div class="xr-var-preview xr-preview">10.0 10.0 10.0 10.0 ... nan nan nan</div><input id="attrs-1f7ef3b4-2a35-4001-a665-077e6d5506e9" class="xr-var-attrs-in" type="checkbox"><label for="attrs-1f7ef3b4-2a35-4001-a665-077e6d5506e9" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-2740d306-14b4-4596-8b7c-448e0df716c7" class="xr-var-data-in" type="checkbox"><label for="data-2740d306-14b4-4596-8b7c-448e0df716c7" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>units :</span></dt><dd>dBm</dd><dt><span>long_name :</span></dt><dd>minimum_transmitted_signal_level_over_time_window</dd></dl></div><div class="xr-var-data"><pre>array([[[10., 10., 10., ..., 10., 10., 10.],
        [10., 10., 10., ..., 10., 10., 10.],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[19., 19., 19., ..., 19., 19., 19.],
        [19., 19., 19., ..., 19., 19., 19.],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[ 8.,  8.,  8., ...,  8.,  8.,  8.],
        [ 8.,  8.,  8., ...,  8.,  8.,  8.],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],
...
       [[ 8.,  8.,  8., ...,  8.,  8.,  8.],
        [ 8.,  8.,  8., ...,  8.,  8.,  8.],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[ 1.,  1.,  1., ...,  1.,  1.,  1.],
        [ 1.,  1.,  1., ...,  1.,  1.,  1.],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[ 1.,  1.,  1., ...,  1.,  1.,  1.],
        [ 1.,  1.,  1., ...,  1.,  1.,  1.],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]], shape=(126, 6, 2964))</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>rsl_max</span></div><div class="xr-var-dims">(cml_id, sublink_id, time)</div><div class="xr-var-dtype">float64</div><div class="xr-var-preview xr-preview">-47.6 -47.8 -47.9 ... nan nan nan</div><input id="attrs-0b162a09-40de-43af-a177-f53409d9318e" class="xr-var-attrs-in" type="checkbox"><label for="attrs-0b162a09-40de-43af-a177-f53409d9318e" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-4926065e-5d66-4e1e-9183-fd7cef0d13b5" class="xr-var-data-in" type="checkbox"><label for="data-4926065e-5d66-4e1e-9183-fd7cef0d13b5" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>units :</span></dt><dd>dBm</dd><dt><span>long_name :</span></dt><dd>maximum_received_signal_level_over_time_window</dd></dl></div><div class="xr-var-data"><pre>array([[[-47.6, -47.8, -47.9, ..., -48. , -47.9, -48. ],
        [-46.2, -46.3, -46.3, ..., -46.2, -46.2, -46.2],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan]],

       [[-43.3, -43.2, -43.2, ..., -39.7, -39.7, -39.7],
        [-42.9, -43.7, -43.7, ..., -95.8, -95.8, -95.8],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan]],

       [[-38.4, -38.3, -38.4, ..., -38.4, -38.5, -38.5],
        [-37.7, -37.7, -37.6, ..., -37.5, -37.6, -37.6],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan]],
...
        [-41.5, -41.5, -41.5, ..., -41.5, -41.5, -41.5],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan]],

       [[-52.8, -52.8, -52.8, ..., -53.1, -53.1, -53.2],
        [-52.7, -52.7, -52.7, ..., -52.9, -52.9, -53. ],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan]],

       [[-45.8, -45.8, -45.8, ..., -46.2, -46.1, -46.1],
        [-45.4, -45.4, -45.4, ..., -46. , -46. , -45.9],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan]]],
      shape=(126, 6, 2964))</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>tsl_max</span></div><div class="xr-var-dims">(cml_id, sublink_id, time)</div><div class="xr-var-dtype">float64</div><div class="xr-var-preview xr-preview">10.0 10.0 10.0 10.0 ... nan nan nan</div><input id="attrs-ff51dd13-9f72-4ddd-a48a-9c62ee9f3bfb" class="xr-var-attrs-in" type="checkbox"><label for="attrs-ff51dd13-9f72-4ddd-a48a-9c62ee9f3bfb" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-4fe38f88-d194-4737-94ee-ce76f487fcbf" class="xr-var-data-in" type="checkbox"><label for="data-4fe38f88-d194-4737-94ee-ce76f487fcbf" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>units :</span></dt><dd>dBm</dd><dt><span>long_name :</span></dt><dd>maximum_transmitted_signal_level_over_time_window</dd></dl></div><div class="xr-var-data"><pre>array([[[10., 10., 10., ..., 10., 10., 10.],
        [10., 10., 10., ..., 10., 10., 10.],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[19., 19., 19., ..., 19., 19., 19.],
        [19., 19., 19., ..., 19., 19., 19.],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[ 8.,  8.,  8., ...,  8.,  8.,  8.],
        [ 8.,  8.,  8., ...,  8.,  8.,  8.],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],
...
       [[ 8.,  8.,  8., ...,  8.,  8.,  8.],
        [ 8.,  8.,  8., ...,  8.,  8.,  8.],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[ 1.,  1.,  1., ...,  1.,  1.,  1.],
        [ 1.,  1.,  1., ...,  1.,  1.,  1.],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[ 1.,  1.,  1., ...,  1.,  1.,  1.],
        [ 1.,  1.,  1., ...,  1.,  1.,  1.],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]], shape=(126, 6, 2964))</pre></div></li></ul></div></li><li class="xr-section-item"><input id="section-32df0598-f99b-4096-b938-2e19b2d39e46" class="xr-section-summary-in" type="checkbox" checked=""><label for="section-32df0598-f99b-4096-b938-2e19b2d39e46" class="xr-section-summary">Attributes: <span>(7)</span></label><div class="xr-section-inline-details"></div><div class="xr-section-details"><dl class="xr-attrs"><dt><span>title :</span></dt><dd>East side Douala CML links sample data</dd><dt><span>file author(s) :</span></dt><dd>Orange Cameroun and IRD Rainsmore Group</dd><dt><span>institution :</span></dt><dd>Orange Cameroun and IRD Rainsmore Group</dd><dt><span>date :</span></dt><dd>2025-11-07</dd><dt><span>source :</span></dt><dd>Modified Orange Cameroun CML data for example purposes</dd><dt><span>naming convention :</span></dt><dd>COST ACTION OPENSENSE V2</dd><dt><span>license restrictions :</span></dt><dd>CC BY-NC-ND 4.0</dd></dl></div></li></ul></div></div>
</div>
</div>
<hr>
<p><a href="https://github.com/rainsmore/raincell/blob/main/raincell/sample.py#L30" target="_blank" style="float:right; font-size:smaller">source</a></p>
</section>
<section id="open_gauge_sample" class="level3">
<h3 class="anchored" data-anchor-id="open_gauge_sample">open_gauge_sample</h3>
<blockquote class="blockquote">
<pre><code> open_gauge_sample ()</code></pre>
</blockquote>
<p><em>Open Sample rain gauge data.</em></p>
<div id="cell-6" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>open_gauge_sample()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div><svg style="position: absolute; width: 0; height: 0; overflow: hidden">
<defs>
<symbol id="icon-database" viewbox="0 0 32 32">
<path d="M16 0c-8.837 0-16 2.239-16 5v4c0 2.761 7.163 5 16 5s16-2.239 16-5v-4c0-2.761-7.163-5-16-5z"></path>
<path d="M16 17c-8.837 0-16-2.239-16-5v6c0 2.761 7.163 5 16 5s16-2.239 16-5v-6c0 2.761-7.163 5-16 5z"></path>
<path d="M16 26c-8.837 0-16-2.239-16-5v6c0 2.761 7.163 5 16 5s16-2.239 16-5v-6c0 2.761-7.163 5-16 5z"></path>
</symbol>
<symbol id="icon-file-text2" viewbox="0 0 32 32">
<path d="M28.681 7.159c-0.694-0.947-1.662-2.053-2.724-3.116s-2.169-2.030-3.116-2.724c-1.612-1.182-2.393-1.319-2.841-1.319h-15.5c-1.378 0-2.5 1.121-2.5 2.5v27c0 1.378 1.122 2.5 2.5 2.5h23c1.378 0 2.5-1.122 2.5-2.5v-19.5c0-0.448-0.137-1.23-1.319-2.841zM24.543 5.457c0.959 0.959 1.712 1.825 2.268 2.543h-4.811v-4.811c0.718 0.556 1.584 1.309 2.543 2.268zM28 29.5c0 0.271-0.229 0.5-0.5 0.5h-23c-0.271 0-0.5-0.229-0.5-0.5v-27c0-0.271 0.229-0.5 0.5-0.5 0 0 15.499-0 15.5 0v7c0 0.552 0.448 1 1 1h7v19.5z"></path>
<path d="M23 26h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z"></path>
<path d="M23 22h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z"></path>
<path d="M23 18h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z"></path>
</symbol>
</defs>
</svg>
<style>/* CSS stylesheet for displaying xarray objects in notebooks */

:root {
  --xr-font-color0: var(
    --jp-content-font-color0,
    var(--pst-color-text-base rgba(0, 0, 0, 1))
  );
  --xr-font-color2: var(
    --jp-content-font-color2,
    var(--pst-color-text-base, rgba(0, 0, 0, 0.54))
  );
  --xr-font-color3: var(
    --jp-content-font-color3,
    var(--pst-color-text-base, rgba(0, 0, 0, 0.38))
  );
  --xr-border-color: var(
    --jp-border-color2,
    hsl(from var(--pst-color-on-background, white) h s calc(l - 10))
  );
  --xr-disabled-color: var(
    --jp-layout-color3,
    hsl(from var(--pst-color-on-background, white) h s calc(l - 40))
  );
  --xr-background-color: var(
    --jp-layout-color0,
    var(--pst-color-on-background, white)
  );
  --xr-background-color-row-even: var(
    --jp-layout-color1,
    hsl(from var(--pst-color-on-background, white) h s calc(l - 5))
  );
  --xr-background-color-row-odd: var(
    --jp-layout-color2,
    hsl(from var(--pst-color-on-background, white) h s calc(l - 15))
  );
}

html[theme="dark"],
html[data-theme="dark"],
body[data-theme="dark"],
body.vscode-dark {
  --xr-font-color0: var(
    --jp-content-font-color0,
    var(--pst-color-text-base, rgba(255, 255, 255, 1))
  );
  --xr-font-color2: var(
    --jp-content-font-color2,
    var(--pst-color-text-base, rgba(255, 255, 255, 0.54))
  );
  --xr-font-color3: var(
    --jp-content-font-color3,
    var(--pst-color-text-base, rgba(255, 255, 255, 0.38))
  );
  --xr-border-color: var(
    --jp-border-color2,
    hsl(from var(--pst-color-on-background, #111111) h s calc(l + 10))
  );
  --xr-disabled-color: var(
    --jp-layout-color3,
    hsl(from var(--pst-color-on-background, #111111) h s calc(l + 40))
  );
  --xr-background-color: var(
    --jp-layout-color0,
    var(--pst-color-on-background, #111111)
  );
  --xr-background-color-row-even: var(
    --jp-layout-color1,
    hsl(from var(--pst-color-on-background, #111111) h s calc(l + 5))
  );
  --xr-background-color-row-odd: var(
    --jp-layout-color2,
    hsl(from var(--pst-color-on-background, #111111) h s calc(l + 15))
  );
}

.xr-wrap {
  display: block !important;
  min-width: 300px;
  max-width: 700px;
  line-height: 1.6;
}

.xr-text-repr-fallback {
  /* fallback to plain text repr when CSS is not injected (untrusted notebook) */
  display: none;
}

.xr-header {
  padding-top: 6px;
  padding-bottom: 6px;
  margin-bottom: 4px;
  border-bottom: solid 1px var(--xr-border-color);
}

.xr-header > div,
.xr-header > ul {
  display: inline;
  margin-top: 0;
  margin-bottom: 0;
}

.xr-obj-type,
.xr-obj-name,
.xr-group-name {
  margin-left: 2px;
  margin-right: 10px;
}

.xr-group-name::before {
  content: "📁";
  padding-right: 0.3em;
}

.xr-group-name,
.xr-obj-type {
  color: var(--xr-font-color2);
}

.xr-sections {
  padding-left: 0 !important;
  display: grid;
  grid-template-columns: 150px auto auto 1fr 0 20px 0 20px;
  margin-block-start: 0;
  margin-block-end: 0;
}

.xr-section-item {
  display: contents;
}

.xr-section-item input {
  display: inline-block;
  opacity: 0;
  height: 0;
  margin: 0;
}

.xr-section-item input + label {
  color: var(--xr-disabled-color);
  border: 2px solid transparent !important;
}

.xr-section-item input:enabled + label {
  cursor: pointer;
  color: var(--xr-font-color2);
}

.xr-section-item input:focus + label {
  border: 2px solid var(--xr-font-color0) !important;
}

.xr-section-item input:enabled + label:hover {
  color: var(--xr-font-color0);
}

.xr-section-summary {
  grid-column: 1;
  color: var(--xr-font-color2);
  font-weight: 500;
}

.xr-section-summary > span {
  display: inline-block;
  padding-left: 0.5em;
}

.xr-section-summary-in:disabled + label {
  color: var(--xr-font-color2);
}

.xr-section-summary-in + label:before {
  display: inline-block;
  content: "►";
  font-size: 11px;
  width: 15px;
  text-align: center;
}

.xr-section-summary-in:disabled + label:before {
  color: var(--xr-disabled-color);
}

.xr-section-summary-in:checked + label:before {
  content: "▼";
}

.xr-section-summary-in:checked + label > span {
  display: none;
}

.xr-section-summary,
.xr-section-inline-details {
  padding-top: 4px;
}

.xr-section-inline-details {
  grid-column: 2 / -1;
}

.xr-section-details {
  display: none;
  grid-column: 1 / -1;
  margin-top: 4px;
  margin-bottom: 5px;
}

.xr-section-summary-in:checked ~ .xr-section-details {
  display: contents;
}

.xr-group-box {
  display: inline-grid;
  grid-template-columns: 0px 20px auto;
  width: 100%;
}

.xr-group-box-vline {
  grid-column-start: 1;
  border-right: 0.2em solid;
  border-color: var(--xr-border-color);
  width: 0px;
}

.xr-group-box-hline {
  grid-column-start: 2;
  grid-row-start: 1;
  height: 1em;
  width: 20px;
  border-bottom: 0.2em solid;
  border-color: var(--xr-border-color);
}

.xr-group-box-contents {
  grid-column-start: 3;
}

.xr-array-wrap {
  grid-column: 1 / -1;
  display: grid;
  grid-template-columns: 20px auto;
}

.xr-array-wrap > label {
  grid-column: 1;
  vertical-align: top;
}

.xr-preview {
  color: var(--xr-font-color3);
}

.xr-array-preview,
.xr-array-data {
  padding: 0 5px !important;
  grid-column: 2;
}

.xr-array-data,
.xr-array-in:checked ~ .xr-array-preview {
  display: none;
}

.xr-array-in:checked ~ .xr-array-data,
.xr-array-preview {
  display: inline-block;
}

.xr-dim-list {
  display: inline-block !important;
  list-style: none;
  padding: 0 !important;
  margin: 0;
}

.xr-dim-list li {
  display: inline-block;
  padding: 0;
  margin: 0;
}

.xr-dim-list:before {
  content: "(";
}

.xr-dim-list:after {
  content: ")";
}

.xr-dim-list li:not(:last-child):after {
  content: ",";
  padding-right: 5px;
}

.xr-has-index {
  font-weight: bold;
}

.xr-var-list,
.xr-var-item {
  display: contents;
}

.xr-var-item > div,
.xr-var-item label,
.xr-var-item > .xr-var-name span {
  background-color: var(--xr-background-color-row-even);
  border-color: var(--xr-background-color-row-odd);
  margin-bottom: 0;
  padding-top: 2px;
}

.xr-var-item > .xr-var-name:hover span {
  padding-right: 5px;
}

.xr-var-list > li:nth-child(odd) > div,
.xr-var-list > li:nth-child(odd) > label,
.xr-var-list > li:nth-child(odd) > .xr-var-name span {
  background-color: var(--xr-background-color-row-odd);
  border-color: var(--xr-background-color-row-even);
}

.xr-var-name {
  grid-column: 1;
}

.xr-var-dims {
  grid-column: 2;
}

.xr-var-dtype {
  grid-column: 3;
  text-align: right;
  color: var(--xr-font-color2);
}

.xr-var-preview {
  grid-column: 4;
}

.xr-index-preview {
  grid-column: 2 / 5;
  color: var(--xr-font-color2);
}

.xr-var-name,
.xr-var-dims,
.xr-var-dtype,
.xr-preview,
.xr-attrs dt {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  padding-right: 10px;
}

.xr-var-name:hover,
.xr-var-dims:hover,
.xr-var-dtype:hover,
.xr-attrs dt:hover {
  overflow: visible;
  width: auto;
  z-index: 1;
}

.xr-var-attrs,
.xr-var-data,
.xr-index-data {
  display: none;
  border-top: 2px dotted var(--xr-background-color);
  padding-bottom: 20px !important;
  padding-top: 10px !important;
}

.xr-var-attrs-in + label,
.xr-var-data-in + label,
.xr-index-data-in + label {
  padding: 0 1px;
}

.xr-var-attrs-in:checked ~ .xr-var-attrs,
.xr-var-data-in:checked ~ .xr-var-data,
.xr-index-data-in:checked ~ .xr-index-data {
  display: block;
}

.xr-var-data > table {
  float: right;
}

.xr-var-data > pre,
.xr-index-data > pre,
.xr-var-data > table > tbody > tr {
  background-color: transparent !important;
}

.xr-var-name span,
.xr-var-data,
.xr-index-name div,
.xr-index-data,
.xr-attrs {
  padding-left: 25px !important;
}

.xr-attrs,
.xr-var-attrs,
.xr-var-data,
.xr-index-data {
  grid-column: 1 / -1;
}

dl.xr-attrs {
  padding: 0;
  margin: 0;
  display: grid;
  grid-template-columns: 125px auto;
}

.xr-attrs dt,
.xr-attrs dd {
  padding: 0;
  margin: 0;
  float: left;
  padding-right: 10px;
  width: auto;
}

.xr-attrs dt {
  font-weight: normal;
  grid-column: 1;
}

.xr-attrs dt:hover span {
  display: inline-block;
  background: var(--xr-background-color);
  padding-right: 10px;
}

.xr-attrs dd {
  grid-column: 2;
  white-space: pre-wrap;
  word-break: break-all;
}

.xr-icon-database,
.xr-icon-file-text2,
.xr-no-icon {
  display: inline-block;
  vertical-align: middle;
  width: 1em;
  height: 1.5em !important;
  stroke-width: 0;
  stroke: currentColor;
  fill: currentColor;
}

.xr-var-attrs-in:checked + label > .xr-icon-file-text2,
.xr-var-data-in:checked + label > .xr-icon-database,
.xr-index-data-in:checked + label > .xr-icon-database {
  color: var(--xr-font-color0);
  filter: drop-shadow(1px 1px 5px var(--xr-font-color2));
  stroke-width: 0.8px;
}
</style><pre class="xr-text-repr-fallback">&lt;xarray.Dataset&gt; Size: 393kB
Dimensions:                  (gauge_name: 8, time: 2881)
Coordinates:
  * gauge_name               (gauge_name) &lt;U25 800B 'Campus_2_Universite' ......
  * time                     (time) datetime64[ns] 23kB 2019-07-01T00:05:00 ....
    gauge_code               (gauge_name) int64 64B 1059095008 ... 1059095001
    gauge_lat                (gauge_name) float64 64B 4.057 4.057 ... 4.047
    gauge_lon                (gauge_name) float64 64B 9.742 9.782 ... 9.746
    gauge_installation_type  (gauge_name) &lt;U10 320B 'Dalle_sol' ... 'equerre'
Data variables:
    tp                       (gauge_name, time) float64 184kB 0.0 0.0 ... 0.0
    tprate                   (gauge_name, time) float64 184kB 0.0 0.0 ... 0.0
Attributes:
    title:                 East side Douala Gauges sample data
    file author(s):        IUT de Douala  and IRD Rainsmore Group
    license restrictions:  CC BY-NC-ND 4.0</pre><div class="xr-wrap" style="display:none"><div class="xr-header"><div class="xr-obj-type">xarray.Dataset</div></div><ul class="xr-sections"><li class="xr-section-item"><input id="section-100b43a4-b074-47e5-955a-76a34862e71f" class="xr-section-summary-in" type="checkbox" disabled=""><label for="section-100b43a4-b074-47e5-955a-76a34862e71f" class="xr-section-summary" title="Expand/collapse section">Dimensions:</label><div class="xr-section-inline-details"><ul class="xr-dim-list"><li><span class="xr-has-index">gauge_name</span>: 8</li><li><span class="xr-has-index">time</span>: 2881</li></ul></div><div class="xr-section-details"></div></li><li class="xr-section-item"><input id="section-88435d86-4cd3-4ae6-bf84-3181a8724dda" class="xr-section-summary-in" type="checkbox" checked=""><label for="section-88435d86-4cd3-4ae6-bf84-3181a8724dda" class="xr-section-summary">Coordinates: <span>(6)</span></label><div class="xr-section-inline-details"></div><div class="xr-section-details"><ul class="xr-var-list"><li class="xr-var-item"><div class="xr-var-name"><span class="xr-has-index">gauge_name</span></div><div class="xr-var-dims">(gauge_name)</div><div class="xr-var-dtype">&lt;U25</div><div class="xr-var-preview xr-preview">'Campus_2_Universite' ... 'SOCATUR'</div><input id="attrs-38b79e2e-bd5c-476d-84f5-c8a4cbaade47" class="xr-var-attrs-in" type="checkbox" disabled=""><label for="attrs-38b79e2e-bd5c-476d-84f5-c8a4cbaade47" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-00368bd5-4a20-472d-9f03-2dba42075c4e" class="xr-var-data-in" type="checkbox"><label for="data-00368bd5-4a20-472d-9f03-2dba42075c4e" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"></dl></div><div class="xr-var-data"><pre>array(['Campus_2_Universite', 'Ecole_Saint_Andre_PK11', 'Eglise_Pie_X_PK14',
       'Hopital_des_Soeurs_Logpom', 'Lycee_NYALLA', 'Meteo_IUT',
       'Piscine_CITE_SIC', 'SOCATUR'], dtype='&lt;U25')</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span class="xr-has-index">time</span></div><div class="xr-var-dims">(time)</div><div class="xr-var-dtype">datetime64[ns]</div><div class="xr-var-preview xr-preview">2019-07-01T00:05:00 ... 2019-07-...</div><input id="attrs-104e7c49-c318-4808-a902-b617c485e66f" class="xr-var-attrs-in" type="checkbox" disabled=""><label for="attrs-104e7c49-c318-4808-a902-b617c485e66f" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-8b1d33a9-10f9-4739-9d9d-a8b10ba42c93" class="xr-var-data-in" type="checkbox"><label for="data-8b1d33a9-10f9-4739-9d9d-a8b10ba42c93" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"></dl></div><div class="xr-var-data"><pre>array(['2019-07-01T00:05:00.000000000', '2019-07-01T00:20:00.000000000',
       '2019-07-01T00:35:00.000000000', ..., '2019-07-30T23:35:00.000000000',
       '2019-07-30T23:50:00.000000000', '2019-07-31T00:05:00.000000000'],
      shape=(2881,), dtype='datetime64[ns]')</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>gauge_code</span></div><div class="xr-var-dims">(gauge_name)</div><div class="xr-var-dtype">int64</div><div class="xr-var-preview xr-preview">1059095008 ... 1059095001</div><input id="attrs-a4695aa8-5283-4bbc-ae91-54bf02d37f87" class="xr-var-attrs-in" type="checkbox" disabled=""><label for="attrs-a4695aa8-5283-4bbc-ae91-54bf02d37f87" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-5713fcb4-3e1e-416a-8da3-f580c319b762" class="xr-var-data-in" type="checkbox"><label for="data-5713fcb4-3e1e-416a-8da3-f580c319b762" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"></dl></div><div class="xr-var-data"><pre>array([1059095008, 1059095004, 1059095007, 1059095005, 1059095002,
       1059095006, 1059095003, 1059095001])</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>gauge_lat</span></div><div class="xr-var-dims">(gauge_name)</div><div class="xr-var-dtype">float64</div><div class="xr-var-preview xr-preview">4.057 4.057 4.079 ... 4.052 4.047</div><input id="attrs-680eb247-dc23-4c5d-9537-b81fd0094ffd" class="xr-var-attrs-in" type="checkbox" disabled=""><label for="attrs-680eb247-dc23-4c5d-9537-b81fd0094ffd" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-101a085e-3d73-4de0-81ef-78c18a80bf8b" class="xr-var-data-in" type="checkbox"><label for="data-101a085e-3d73-4de0-81ef-78c18a80bf8b" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"></dl></div><div class="xr-var-data"><pre>array([4.05663859, 4.05686995, 4.079149  , 4.078547  , 4.031468  ,
       4.056894  , 4.051833  , 4.047314  ])</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>gauge_lon</span></div><div class="xr-var-dims">(gauge_name)</div><div class="xr-var-dtype">float64</div><div class="xr-var-preview xr-preview">9.742 9.782 9.795 ... 9.731 9.746</div><input id="attrs-94e60675-a601-4934-878b-c266e4b8194c" class="xr-var-attrs-in" type="checkbox" disabled=""><label for="attrs-94e60675-a601-4934-878b-c266e4b8194c" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-9fac1032-452f-4a08-9f53-ed2b777abe22" class="xr-var-data-in" type="checkbox"><label for="data-9fac1032-452f-4a08-9f53-ed2b777abe22" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"></dl></div><div class="xr-var-data"><pre>array([9.74233361, 9.7816409 , 9.794725  , 9.767835  , 9.769916  ,
       9.745173  , 9.730603  , 9.745514  ])</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>gauge_installation_type</span></div><div class="xr-var-dims">(gauge_name)</div><div class="xr-var-dtype">&lt;U10</div><div class="xr-var-preview xr-preview">'Dalle_sol' 'equerre' ... 'equerre'</div><input id="attrs-a52228d6-b940-4d63-b670-575e4bcf7b90" class="xr-var-attrs-in" type="checkbox" disabled=""><label for="attrs-a52228d6-b940-4d63-b670-575e4bcf7b90" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-1fa0ccf1-90c2-4f3d-8ab1-85b0055cbf68" class="xr-var-data-in" type="checkbox"><label for="data-1fa0ccf1-90c2-4f3d-8ab1-85b0055cbf68" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"></dl></div><div class="xr-var-data"><pre>array(['Dalle_sol', 'equerre', 'equerre', 'Dalle_sol', 'Dalle_sol',
       'Dalle_sol', 'Dalle_toit', 'equerre'], dtype='&lt;U10')</pre></div></li></ul></div></li><li class="xr-section-item"><input id="section-e46e8df1-131c-4116-99d0-f423f47acb93" class="xr-section-summary-in" type="checkbox" checked=""><label for="section-e46e8df1-131c-4116-99d0-f423f47acb93" class="xr-section-summary">Data variables: <span>(2)</span></label><div class="xr-section-inline-details"></div><div class="xr-section-details"><ul class="xr-var-list"><li class="xr-var-item"><div class="xr-var-name"><span>tp</span></div><div class="xr-var-dims">(gauge_name, time)</div><div class="xr-var-dtype">float64</div><div class="xr-var-preview xr-preview">0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0</div><input id="attrs-9f7aabe3-c46f-4aa4-bbf9-d88cd5b90280" class="xr-var-attrs-in" type="checkbox" disabled=""><label for="attrs-9f7aabe3-c46f-4aa4-bbf9-d88cd5b90280" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-c65ab543-751b-4af1-9a44-16b573e7710b" class="xr-var-data-in" type="checkbox"><label for="data-c65ab543-751b-4af1-9a44-16b573e7710b" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"></dl></div><div class="xr-var-data"><pre>array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(8, 2881))</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>tprate</span></div><div class="xr-var-dims">(gauge_name, time)</div><div class="xr-var-dtype">float64</div><div class="xr-var-preview xr-preview">0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0</div><input id="attrs-85797c03-b501-45c5-b378-0c19b4e6ac0b" class="xr-var-attrs-in" type="checkbox" disabled=""><label for="attrs-85797c03-b501-45c5-b378-0c19b4e6ac0b" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-272dbb1c-995a-4af4-95f4-3db8270f10ce" class="xr-var-data-in" type="checkbox"><label for="data-272dbb1c-995a-4af4-95f4-3db8270f10ce" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"></dl></div><div class="xr-var-data"><pre>array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(8, 2881))</pre></div></li></ul></div></li><li class="xr-section-item"><input id="section-76de34fd-f2d4-44dc-a609-0868dfb7f213" class="xr-section-summary-in" type="checkbox" checked=""><label for="section-76de34fd-f2d4-44dc-a609-0868dfb7f213" class="xr-section-summary">Attributes: <span>(3)</span></label><div class="xr-section-inline-details"></div><div class="xr-section-details"><dl class="xr-attrs"><dt><span>title :</span></dt><dd>East side Douala Gauges sample data</dd><dt><span>file author(s) :</span></dt><dd>IUT de Douala  and IRD Rainsmore Group</dd><dt><span>license restrictions :</span></dt><dd>CC BY-NC-ND 4.0</dd></dl></div></li></ul></div></div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/rainsmore\.github\.io\/raincell");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/rainsmore/raincell/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>