"""The objective of this modeule is to create some helper function to help us set the correct center and zoom level in `folium` (and other) maps."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/22_maps.helpers.ipynb.

# %% auto 0
__all__ = ['get_center', 'get_zoom_start']

# %% ../../nbs/22_maps.helpers.ipynb 2
import math

import numpy as np
import xarray as xr

from .. import open_cml_sample

# %% ../../nbs/22_maps.helpers.ipynb 7
def get_center(cml: xr.DataArray | xr.Dataset) -> tuple[float,float]:
    """ Get the center point of a set of CML in OpenSense standard """
    lats = np.concat([cml["site_0_lat"].values, cml["site_1_lat"].values])
    lons = np.concat([cml["site_0_lon"].values, cml["site_1_lon"].values])
    return float(lats.min() + lats.max()) / 2, float(lons.min() + lons.max()) / 2

# %% ../../nbs/22_maps.helpers.ipynb 10
def _get_lat_zoom_start(cml, height=800):
    v0 = 78271.484
    equator_decimal_deg_2_m = 111320
    height += 50 # add some margin
    lats = np.concat([cml["site_0_lat"].values, cml["site_1_lat"].values])
    min_lat, max_lat = float(lats.min()), float(lats.max())
    zoom_level = math.log2(v0 * height * math.cos(math.radians((max_lat + min_lat) / 2)) / (abs(max_lat - min_lat) * equator_decimal_deg_2_m))
    return zoom_level - 0.15 # add some margin

# %% ../../nbs/22_maps.helpers.ipynb 12
def _get_lon_zoom_start(cml, width=600):
    v0 = 78271.484
    equator_decimal_deg_2_m = 111320
    width += 50
    lons = np.concat([cml["site_0_lon"].values, cml["site_1_lon"].values])
    lons_min, lons_max = float(lons.min()), float(lons.max())
    zoom_level = math.log2(v0 * width / (abs(lons_max - lons_min) * equator_decimal_deg_2_m))
    return zoom_level - 0.15 # add some margin

# %% ../../nbs/22_maps.helpers.ipynb 14
def get_zoom_start(cml, height=1200, width=1200):
    return min(_get_lat_zoom_start(cml, height), _get_lon_zoom_start(cml, width))
