"""Romulo plots are heatmaps designed to give a quick overview of CML (commercial microwave link) variables across time and sublinks — useful to spot attenuation bursts, sensor issues or systematic patterns - and to compare them with gauge data."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/20_plot.romulo.ipynb.

# %% auto 0
__all__ = ['romulo_plot_cml', 'romulo_plot_gauges', 'romulo_plot']

# %% ../../nbs/20_plot.romulo.ipynb 3
import xarray as xr
import matplotlib.pyplot as plt
from .. import open_cml_sample, open_gauge_sample

# %% ../../nbs/20_plot.romulo.ipynb 9
def reduce_cml_id_dim(
    cml: xr.DataArray | xr.Dataset, # CML in OpenSense standard
    drop_allna: bool = True # Drop sublinks with all nan values in time
    ) -> xr.DataArray | xr.Dataset:
    """Reduce one CML data dimension by combining cml_id and sublink_id dims into a single `sublink_id` dimension."""
    stacked = cml.stack(sublink=('cml_id', 'sublink_id'))
    new_index = [f"{cml}__{sub}" for cml, sub in stacked.sublink.values]
    reindexed = stacked.drop_vars(['cml_id', 'sublink_id', 'sublink']).assign_coords(sublink=new_index)
    reindexed = reindexed.rename({"sublink": "sublink_id"})
    return  reindexed.dropna(dim='sublink_id', how='all') if drop_allna else reindexed

# %% ../../nbs/20_plot.romulo.ipynb 21
def romulo_plot_cml(
        cml: xr.DataArray, # CML data to plot
        title: str = None, # Title for the plot
        fig: plt.Figure = None, 
        ax: plt.Axes = None, 
        figsize: tuple = (16, 9), # Figure size, only used if fig or ax are None
        vmax: float | None = None # Maximum value for colormap
        ) -> tuple[plt.Figure, plt.Axes]:
    """Plot an overview of the CML data sorted by length. Negative values, which are not phisically possible are shown in red."""
    cml_sorted = reduce_cml_id_dim(cml).sortby("length")
    
    cmap = plt.cm.Blues.copy()
    cmap.set_under('red')
    
    if fig is None or ax is None:
        fig, ax = plt.subplots(figsize=figsize)
    cml_sorted.plot(ax=ax, x="time", vmin=0, vmax=vmax,cmap=cmap, extend='min')
    
    ax.set_yticks([])
    ax.set_ylabel("Sublink data sorted by length")
    ax.set_title(title or cml.name)
    
    return fig, ax

# %% ../../nbs/20_plot.romulo.ipynb 33
def romulo_plot_gauges(
        gauges: xr.DataArray, # Gauge data to plot
        fig: plt.Figure = None, 
        ax: plt.Axes = None, 
        figsize: tuple = (12, 2), # Figure size, only used if fig or ax are None
        vmax: float = 4, # Maximum value for colormap
        ) -> tuple[plt.Figure, plt.Axes]:
    """Plot data as a heatmap with grid lines separating each gauge."""
    dims = [d for d in gauges.dims if d != "time"]
    if len(dims) != 1:
        raise ValueError(f"Expected exactly one non-time dimension, found {len(dims)}: {dims}")
    id_dim = dims[0]

    cmap = plt.cm.Blues.copy()
    cmap.set_under('red')
    
    if fig is None or ax is None:
        fig, ax = plt.subplots(figsize=figsize)
    
    gauges.plot(ax=ax, x="time", cmap=cmap, vmin=0, vmax=vmax)
    ax.set_ylim(ax.get_ylim()[0] - 0.5, ax.get_ylim()[1] + 0.5)
    ax.set_yticks([i + 0.5 for i in range(gauges[id_dim].size - 1)], minor=True)
    ax.grid(which='minor', axis='y')
    ax.set_ylabel("Gauge")
    
    return fig, ax


# %% ../../nbs/20_plot.romulo.ipynb 37
def romulo_plot(
    cml: xr.DataArray, # CML raw or derived data in OpenSense standard
    gauges: xr.DataArray, # Rain gauges data as 2D data array
    title: str | None = None,
    figsize: tuple = (16, 9),
    ratio: int = 4, # Ratio of the CML plot vs Gauges plot
    cml_vmax: float | None = None, # Maximum value for CML colormap
    gauges_vmax: float = 4, # Maximum value for Gauges colormap
    ) -> tuple[plt.Figure, plt.Axes, plt.Axes]:
    fig, (ax_cml, ax_gauges) = plt.subplots(nrows=2, sharex=True, figsize=figsize, gridspec_kw={'height_ratios': [ratio, 1]})
    romulo_plot_cml(cml, title=title, fig=fig, ax=ax_cml, vmax=cml_vmax)
    romulo_plot_gauges(gauges, fig=fig, ax=ax_gauges, vmax=gauges_vmax)
    return fig, ax_cml, ax_gauges
