# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/raincell',
                'doc_host': 'https://rainsmore.github.io',
                'git_url': 'https://github.com/rainsmore/raincell',
                'lib_path': 'raincell'},
  'syms': {'raincell.core': {'raincell.core.foo': ('core.html#foo', 'raincell/core.py')}}}
