"""This module groups the methods related to the baseline estimation."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/11_baseline.ipynb.

# %% auto 0
__all__ = ['get_bl_as_last_dry_step']

# %% ../nbs/11_baseline.ipynb 2
import inspect
import xarray as xr

# %% ../nbs/11_baseline.ipynb 18
def get_bl_as_last_dry_step(
        att: xr.Dataset, # ds containing the raw attenuation variables
        wet: xr.DataArray # da containing wet events as booleans
        ) -> xr.Dataset: # ds containing the baseline of all the attenuation variables in the input
    """Create a baseline based on the last dry step before the each wet event."""
    baseline = att.where(~wet).ffill(dim="time")
    for v in baseline.data_vars:
        attrs = baseline[v].attrs
        attrs["long_name"] = getattr(attrs, "long_name", v) + "_baseline"    
        attrs["method"] = inspect.currentframe().f_code.co_name
    return baseline
