"""This module groups the methods related to the baseline estimation."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/11_baseline.ipynb.

# %% auto 0
__all__ = ['get_bl_as_last_dry_step']

# %% ../nbs/11_baseline.ipynb 2
import inspect
import xarray as xr

# %% ../nbs/11_baseline.ipynb 16
def get_bl_as_last_dry_step(
        att: xr.Dataset|xr.DataArray, # ds containing the raw attenuation variables
        wet: xr.DataArray # da containing wet events as booleans
        ) -> xr.Dataset|xr.DataArray: # ds containing the baseline of all the attenuation variables in the input
    """Create a baseline based on the last dry step before the each wet event."""
    def updated_attrs(da, method):
        return {"long_name": getattr(da.attrs, "long_name", v) + "_baseline", "method": method}
    baseline = att.where(~wet).ffill(dim="time")
    fname = inspect.currentframe().f_code.co_name
    if isinstance(att, xr.DataArray):
        baseline.attrs = {**baseline.attrs, **updated_attrs(baseline, fname)}
    else:
        for v in baseline.data_vars:
            baseline[v].attrs = {**baseline[v].attrs, **updated_attrs(baseline[v], fname)}
    return baseline
