"""This module contains methods for estimating rain rates from path-integrated attenuation (PIA). Currently, we compute the time-mean total precipitation rate as defined by [ECMWF](https://codes.ecmwf.int/grib/param-db/172228), using `tprate` as the variable name for simplicity. Note that while ECMWF uses units of $m·s^{-1}$, we may use different units such as $mm·h^{-1}$."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/13_rain_rate.ipynb.

# %% auto 0
__all__ = ['alcoba_2019_africa_coefs', 'get_overeem_et_al_2013_min_max_sampling_tprate']

# %% ../nbs/13_rain_rate.ipynb 2
import pandas as pd
import xarray as xr

# %% ../nbs/13_rain_rate.ipynb 7
def alcoba_2019_africa_coefs() -> xr.Dataset:
    """ k-R relationship coefficients for Africa from [Alcoba (2019)](https://theses.hal.science/tel-02955598/). """
    coefs = {
        "7.0":{"a":0.000197,"b":1.854},
        "8.5":{"a":0.0066,"b":1.2897},
        "11.0":{"a":0.0195,"b":1.1951},
        "11.5":{"a":0.023,"b":1.1775},
        "13.0":{"a":0.0347,"b":1.1333},
        "14.5":{"a":0.0473,"b":1.1022},
        "15.0":{"a":0.0517,"b":1.0943},
        "18.0":{"a":0.0781,"b":1.0654},
        "19.0":{"a":0.0873,"b":1.06},
        "22.0":{"a":0.1171,"b":1.0471},
        "23.0":{"a":0.1281,"b":1.0428}
        }

    coefs = xr.Dataset(
        data_vars={
            "a": ("frequency", [c["a"] for c in coefs.values()]),
            "b": ("frequency", [c["b"] for c in coefs.values()])
        },
        coords={"frequency": [float(f) * 1e3 for f in coefs.keys()]} # Convert to MHz to match OpenSense standard
    )
    coefs["frequency"].attrs["units"] = "MHz"
    return coefs   

# %% ../nbs/13_rain_rate.ipynb 17
def reindex_coefs(
        pia: xr.Dataset, # ds containing path integrated attenuation
        coefs: xr.Dataset # ds containing a and b, k-R law coefficients with frequency dim
    ):
    """Reindex k-R coefficients to match the path integrated attenuation dataset."""
    coefs = coefs.sel(frequency=pia.frequency, method="nearest")
    return coefs.drop([c for c in coefs.coords if c not in coefs.dims])

# %% ../nbs/13_rain_rate.ipynb 24
def get_overeem_et_al_2013_min_max_sampling_tprate(
        pia: xr.Dataset, # ds containing path integrated attenuation with Amin and Amax variables
        cfs: xr.Dataset, # ds containing a and b, k-R law coefficients with frequency dim
        alpha: float = 0.3 # weighting factor between max and min sampling rain rates
    ) -> xr.Dataset:
    """Compute the rain rate using the Overeem et al. (2013) min/max sampling approach. """
    def kR(pia, a, b, l):
        return a * (pia / (l / 1e3)) ** b # Convert OpenSense standard length in meters to km
    H = pia > 0
    cfs = reindex_coefs(pia, cfs)

    Rmin = kR(pia["Amin"], cfs.a, cfs.b, pia.length).where(H["Amin"])
    Rmax = kR(pia["Amax"], cfs.a, cfs.b, pia.length).where(H["Amax"])

    tprate = (alpha * Rmax + (1 - alpha) * Rmin).to_dataset(name="tprate")
    tprate["tprate"].attrs = {"long_name": "time_mean_path_averaged_rain_rate", "units": "mm/h"}
    return tprate
