"""This module groups all the functions and methods related to sample data that will be used to develop the raincell library."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_sample_data.ipynb.

# %% auto 0
__all__ = ['open_cml_sample', 'open_sample_gauges']

# %% ../nbs/01_sample_data.ipynb 3
import xarray as xr

from .config import SAMPLE_DATA_DIR

# %% ../nbs/01_sample_data.ipynb 4
def open_cml_sample() -> xr.Dataset:
    """Open Sample Commercial Microwave Link (CML) data.""" 
    return xr.load_dataset(SAMPLE_DATA_DIR / "cml_douala.nc")

# %% ../nbs/01_sample_data.ipynb 6
def open_sample_gauges() -> xr.Dataset:
    """Open Sample rain gauge data.""" 
    return xr.load_dataset(SAMPLE_DATA_DIR / "gauges_douala.nc")
