"""This module groups the methods related to wet antenna attenuation."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/12_waa.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/12_waa.ipynb 2
import xarray as xr
