"""This module groups the methods related to wet antenna attenuation."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/12_waa.ipynb.

# %% auto 0
__all__ = ['rm_constant_waa']

# %% ../nbs/12_waa.ipynb 2
import xarray as xr

# %% ../nbs/12_waa.ipynb 4
def rm_constant_waa(
        att: xr.Dataset, # ds containing the attenuation time series
        waa: float = 2.3 # dB constant wet antenna attenuation
) -> xr.Dataset:
     """ Remove a constant wet antenna attenuation from the attenuation time series. """
     return att - waa
