"""This module groups the methods related to wet/dry classification of the CML signal."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_wetdry.ipynb.

# %% auto 0
__all__ = ['schleiss_n_berne_2010_nms_adapted']

# %% ../nbs/10_wetdry.ipynb 2
import xarray as xr

# %% ../nbs/10_wetdry.ipynb 11
def schleiss_n_berne_2010_nms_adapted(
        cml: xr.Dataset, # Input CML dataset with tsl_max and rsl_min variables
        r: float = 0.1 # Fraction of time it is assumed to be raining
        ) -> xr.Dataset:
    """ Wet Dry classification algorithm adapted to work with NMS sampling adapted from Schleiss et al., 2010. """
    sw = cml["tsl_max"] - cml["rsl_min"]
    sigma0 = sw.quantile(q=(1-r), dim="time")
    wet = sw >= sigma0
    wet = wet.drop_vars("quantile")
    wet.attrs["long_name"] = "wet_dry_classification"
    wet.attrs["method"] = "schleiss_n_berne_2010_adapted_to_nms_min_max_sampling"
    return wet.to_dataset(name="wet")
