"""This module groups the methods related to wet/dry classification of the CML signal."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_wetdry.ipynb.

# %% auto 0
__all__ = ['schleiss_n_berne_2010_nms_adapted']

# %% ../nbs/10_wetdry.ipynb 2
import numpy as np
import xarray as xr

# %% ../nbs/10_wetdry.ipynb 13
def schleiss_n_berne_2010_nms_adapted(
        cml: xr.Dataset, # Input CML dataset with tsl_max and rsl_min variables
        r: float = 0.1 # Fraction of time it is assumed to be raining
        ) -> xr.Dataset:
    """ Wet Dry classification algorithm adapted to work with NMS sampling adapted from Schleiss and Berne (2010). """
    sw = cml["tsl_max"] - cml["rsl_min"]
    all_nan_in_time = ~sw.isnull().all(dim="time")
    sigma0 = sw.fillna(-9999).quantile(q=(1-r), dim="time").where(all_nan_in_time) # Rm runetime warning
    wet = sw >= sigma0
    wet = wet.drop_vars("quantile")
    wet.name = "wet"
    wet.attrs["long_name"] = "wet_dry_classification"
    wet.attrs["method"] = "schleiss_n_berne_2010_adapted_to_nms_min_max_sampling"
    return wet
